import type {
  BusOption,
  FlightOption,
  HotelListing,
  OfferItem,
  TourPackage,
  TrainOption,
  TravelBooking,
  WalletTxn,
} from './types';

export function formatInr(amount: number) {
  return `₹${amount.toLocaleString('en-IN')}`;
}

export const cities = [
  'Mumbai',
  'Delhi',
  'Bengaluru',
  'Goa',
  'Jaipur',
  'Kochi',
  'Hyderabad',
  'Chennai',
  'Dubai',
  'Singapore',
  'Bangkok',
  'Bali',
];

export const demoPackages: TourPackage[] = [
  {
    id: 'pkg-dom-01',
    name: 'Goa Coastal Escape',
    destination: 'Goa',
    category: 'domestic',
    nights: 3,
    days: 4,
    priceFrom: 18999,
    rating: 4.6,
    highlights: ['Beach resorts', 'Sunset cruise', 'Local cuisine walk'],
    inclusions: ['Stay', 'Breakfast', 'Airport transfers', '1 activity'],
    exclusions: ['Flights', 'Personal expenses', 'Optional watersports'],
    itinerary: [
      { day: 1, title: 'Arrive & unwind', summary: 'Check-in, beach evening, welcome dinner suggestion.' },
      { day: 2, title: 'North Goa circuit', summary: 'Fort views, markets, and free evening.' },
      { day: 3, title: 'Cruise & leisure', summary: 'Optional cruise, spa time, beach clubs.' },
      { day: 4, title: 'Departure', summary: 'Breakfast and airport transfer.' },
    ],
    imageTone: 'from-sky-500/30 to-cyan-600/20',
  },
  {
    id: 'pkg-dom-02',
    name: 'Rajasthan Heritage Trail',
    destination: 'Jaipur · Udaipur',
    category: 'domestic',
    nights: 5,
    days: 6,
    priceFrom: 32999,
    rating: 4.8,
    highlights: ['Palace visits', 'Desert evening', 'City walks'],
    inclusions: ['4★ stays', 'Breakfast', 'Guided sightseeing', 'Intercity transfer'],
    exclusions: ['Flights', 'Lunch/dinner', 'Monument tickets where paid'],
    itinerary: [
      { day: 1, title: 'Jaipur arrival', summary: 'Check-in and local market stroll.' },
      { day: 2, title: 'Pink City', summary: 'Fort and palace circuit with guide.' },
      { day: 3, title: 'Transfer to Udaipur', summary: 'Scenic drive and lake-side evening.' },
      { day: 4, title: 'Lake city', summary: 'Boat ride and heritage walks.' },
      { day: 5, title: 'Leisure day', summary: 'Optional spa or countryside visit.' },
      { day: 6, title: 'Departure', summary: 'Checkout and onward transfer.' },
    ],
    imageTone: 'from-amber-500/25 to-orange-700/20',
  },
  {
    id: 'pkg-int-01',
    name: 'Dubai City Lights',
    destination: 'Dubai',
    category: 'international',
    nights: 4,
    days: 5,
    priceFrom: 54999,
    rating: 4.7,
    highlights: ['Desert safari', 'Skyline views', 'Mall & marina evenings'],
    inclusions: ['Hotel', 'Breakfast', 'Airport transfers', 'Desert safari'],
    exclusions: ['Airfare', 'Visa fees', 'Theme parks'],
    itinerary: [
      { day: 1, title: 'Arrive Dubai', summary: 'Transfer and marina evening.' },
      { day: 2, title: 'City icons', summary: 'Guided city tour and photo stops.' },
      { day: 3, title: 'Desert night', summary: 'Safari with camp dinner experience.' },
      { day: 4, title: 'Free day', summary: 'Shopping or optional attractions.' },
      { day: 5, title: 'Depart', summary: 'Checkout and airport transfer.' },
    ],
    imageTone: 'from-violet-500/25 to-fuchsia-600/15',
  },
  {
    id: 'pkg-int-02',
    name: 'Singapore Family Fun',
    destination: 'Singapore',
    category: 'family',
    nights: 4,
    days: 5,
    priceFrom: 62999,
    rating: 4.9,
    highlights: ['Theme park day', 'Gardens', 'Sentosa evening'],
    inclusions: ['Hotel', 'Breakfast', 'Airport transfers', '1 park ticket set'],
    exclusions: ['Airfare', 'Meals', 'Optional cable car'],
    itinerary: [
      { day: 1, title: 'Arrival', summary: 'Settle in and light exploration.' },
      { day: 2, title: 'Theme park', summary: 'Full-day family attractions.' },
      { day: 3, title: 'City & gardens', summary: 'Skyline and botanical stops.' },
      { day: 4, title: 'Island evening', summary: 'Beach and light shows.' },
      { day: 5, title: 'Return', summary: 'Checkout and flight transfer.' },
    ],
    imageTone: 'from-emerald-500/25 to-teal-600/20',
  },
  {
    id: 'pkg-hm-01',
    name: 'Bali Honeymoon Escape',
    destination: 'Bali',
    category: 'honeymoon',
    nights: 5,
    days: 6,
    priceFrom: 71999,
    rating: 4.8,
    highlights: ['Private villa night', 'Sunset dinner', 'Spa couple session'],
    inclusions: ['Boutique stays', 'Breakfast', 'Airport transfers', '1 spa'],
    exclusions: ['Flights', 'Visa on arrival fees', 'Adventure add-ons'],
    itinerary: [
      { day: 1, title: 'Ubud arrival', summary: 'Rice terrace welcome.' },
      { day: 2, title: 'Culture day', summary: 'Temple circuit and cafe evenings.' },
      { day: 3, title: 'Transfer to coast', summary: 'Beach check-in and sunset.' },
      { day: 4, title: 'Leisure & spa', summary: 'Couple spa and private dinner.' },
      { day: 5, title: 'Free day', summary: 'Optional water activities.' },
      { day: 6, title: 'Departure', summary: 'Airport transfer.' },
    ],
    imageTone: 'from-rose-400/25 to-pink-600/20',
  },
  {
    id: 'pkg-ad-01',
    name: 'Himalayan Adventure Base',
    destination: 'Manali · Solang',
    category: 'adventure',
    nights: 4,
    days: 5,
    priceFrom: 24999,
    rating: 4.5,
    highlights: ['Trek day', 'River activity', 'Camp night option'],
    inclusions: ['Stay', 'Breakfast', 'Local transfers', '1 adventure activity'],
    exclusions: ['Flights', 'Gear rental extras', 'Personal insurance'],
    itinerary: [
      { day: 1, title: 'Arrive Manali', summary: 'Acclimatize and town walk.' },
      { day: 2, title: 'Solang valley', summary: 'Adventure activities block.' },
      { day: 3, title: 'Trek day', summary: 'Guided short trek with picnic.' },
      { day: 4, title: 'Leisure', summary: 'Cafe hopping and optional camp.' },
      { day: 5, title: 'Depart', summary: 'Checkout and transfer.' },
    ],
    imageTone: 'from-blue-500/25 to-slate-600/25',
  },
  {
    id: 'pkg-pil-01',
    name: 'Char Dham Circuit Preview',
    destination: 'Uttarakhand',
    category: 'pilgrimage',
    nights: 6,
    days: 7,
    priceFrom: 38999,
    rating: 4.4,
    highlights: ['Guided darshan support', 'Comfort stays', 'Local transport'],
    inclusions: ['Hotels', 'Breakfast & dinner', 'AC coach segments', 'Coordinator'],
    exclusions: ['Helicopter options', 'Personal offerings', 'Porter tips'],
    itinerary: [
      { day: 1, title: 'Haridwar base', summary: 'Orientation and aarti evening.' },
      { day: 2, title: 'Transit day', summary: 'Scenic transfer and rest.' },
      { day: 3, title: 'Temple visit 1', summary: 'Darshan window with buffer time.' },
      { day: 4, title: 'Temple visit 2', summary: 'Guided schedule and rest.' },
      { day: 5, title: 'Temple visit 3', summary: 'Coordinator-supported flow.' },
      { day: 6, title: 'Return transit', summary: 'Descent and overnight.' },
      { day: 7, title: 'Depart', summary: 'Checkout assistance.' },
    ],
    imageTone: 'from-orange-400/20 to-yellow-600/15',
  },
];

export const demoHotels: HotelListing[] = [
  {
    id: 'htl-01',
    name: 'Harbor View Demo Hotel',
    city: 'Goa',
    rating: 4.6,
    reviews: 312,
    pricePerNight: 4200,
    amenities: ['Pool', 'Breakfast', 'Wi-Fi', 'Spa', 'Airport shuttle'],
    roomTypes: [
      { name: 'Deluxe Twin', price: 4200, capacity: 2 },
      { name: 'Ocean Suite', price: 7800, capacity: 3 },
      { name: 'Family Room', price: 6500, capacity: 4 },
    ],
    gallery: ['Lobby atrium', 'Pool deck', 'Ocean suite', 'Breakfast hall'],
    distance: '1.8 km from beach',
  },
  {
    id: 'htl-02',
    name: 'Pink City Courtyard Stay',
    city: 'Jaipur',
    rating: 4.4,
    reviews: 188,
    pricePerNight: 3600,
    amenities: ['Wi-Fi', 'Restaurant', 'Parking', 'Concierge'],
    roomTypes: [
      { name: 'Heritage Room', price: 3600, capacity: 2 },
      { name: 'Courtyard Deluxe', price: 4900, capacity: 2 },
    ],
    gallery: ['Courtyard', 'Heritage room', 'Rooftop cafe'],
    distance: '2.1 km from city center',
  },
  {
    id: 'htl-03',
    name: 'Marina Skyline Residences',
    city: 'Dubai',
    rating: 4.8,
    reviews: 540,
    pricePerNight: 9800,
    amenities: ['Pool', 'Gym', 'Wi-Fi', 'Kitchenette', 'City view'],
    roomTypes: [
      { name: 'Studio Marina', price: 9800, capacity: 2 },
      { name: '1BHK Skyline', price: 14500, capacity: 3 },
    ],
    gallery: ['Skyline view', 'Pool infinity edge', 'Lobby lounge'],
    distance: '0.6 km from marina walk',
  },
  {
    id: 'htl-04',
    name: 'Garden Bay Family Hotel',
    city: 'Singapore',
    rating: 4.5,
    reviews: 276,
    pricePerNight: 8200,
    amenities: ['Breakfast', 'Kids corner', 'Wi-Fi', 'Laundry'],
    roomTypes: [
      { name: 'Superior Twin', price: 8200, capacity: 2 },
      { name: 'Family Quad', price: 11800, capacity: 4 },
    ],
    gallery: ['Garden court', 'Family room', 'Breakfast buffet'],
    distance: '1.2 km from metro',
  },
];

export const demoFlights: FlightOption[] = [
  {
    id: 'flt-01',
    airline: 'Demo Air',
    flightNo: 'DA 214',
    from: 'BOM',
    to: 'GOI',
    depart: '07:20',
    arrive: '08:35',
    duration: '1h 15m',
    stops: 0,
    fare: 4899,
    cabin: 'Economy',
    refundable: false,
  },
  {
    id: 'flt-02',
    airline: 'Skyline Demo',
    flightNo: 'SD 908',
    from: 'BOM',
    to: 'GOI',
    depart: '11:45',
    arrive: '13:10',
    duration: '1h 25m',
    stops: 0,
    fare: 5620,
    cabin: 'Economy',
    refundable: true,
  },
  {
    id: 'flt-03',
    airline: 'Demo Air',
    flightNo: 'DA 551',
    from: 'DEL',
    to: 'DXB',
    depart: '22:10',
    arrive: '00:40+1',
    duration: '3h 30m',
    stops: 0,
    fare: 18450,
    cabin: 'Economy',
    refundable: true,
  },
  {
    id: 'flt-04',
    airline: 'Pacific Demo',
    flightNo: 'PD 331',
    from: 'BLR',
    to: 'SIN',
    depart: '01:15',
    arrive: '07:55',
    duration: '4h 40m',
    stops: 0,
    fare: 22100,
    cabin: 'Premium Economy',
    refundable: true,
  },
  {
    id: 'flt-05',
    airline: 'Skyline Demo',
    flightNo: 'SD 112',
    from: 'DEL',
    to: 'BOM',
    depart: '06:00',
    arrive: '08:05',
    duration: '2h 05m',
    stops: 0,
    fare: 6100,
    cabin: 'Economy',
    refundable: false,
  },
];

export const demoTrains: TrainOption[] = [
  {
    id: 'trn-01',
    name: 'Coastal Demo Express',
    number: '12001',
    from: 'CSMT',
    to: 'MAO',
    depart: '23:05',
    arrive: '10:40+1',
    duration: '11h 35m',
    classes: [
      { name: '3A', fare: 1890, seats: 24 },
      { name: '2A', fare: 2680, seats: 12 },
      { name: 'SL', fare: 720, seats: 48 },
    ],
  },
  {
    id: 'trn-02',
    name: 'Capital Demo Shatabdi',
    number: '12002',
    from: 'NDLS',
    to: 'JP',
    depart: '06:05',
    arrive: '10:35',
    duration: '4h 30m',
    classes: [
      { name: 'CC', fare: 980, seats: 36 },
      { name: 'EC', fare: 1850, seats: 18 },
    ],
  },
  {
    id: 'trn-03',
    name: 'Southern Demo Mail',
    number: '12615',
    from: 'MAS',
    to: 'SBC',
    depart: '22:40',
    arrive: '04:55+1',
    duration: '6h 15m',
    classes: [
      { name: '3A', fare: 1450, seats: 30 },
      { name: 'SL', fare: 540, seats: 60 },
    ],
  },
];

export const demoBuses: BusOption[] = [
  {
    id: 'bus-01',
    operator: 'Demo Trails',
    from: 'Mumbai',
    to: 'Goa',
    depart: '20:30',
    arrive: '08:00+1',
    duration: '11h 30m',
    type: 'Volvo AC Sleeper',
    fare: 1450,
    seats: 18,
  },
  {
    id: 'bus-02',
    operator: 'Coastline Demo',
    from: 'Bengaluru',
    to: 'Goa',
    depart: '21:15',
    arrive: '07:45+1',
    duration: '10h 30m',
    type: 'AC Seater/Sleeper',
    fare: 1299,
    seats: 22,
  },
  {
    id: 'bus-03',
    operator: 'Desert Route Demo',
    from: 'Delhi',
    to: 'Jaipur',
    depart: '07:00',
    arrive: '12:20',
    duration: '5h 20m',
    type: 'AC Seater',
    fare: 650,
    seats: 28,
  },
];

export const demoOffers: OfferItem[] = [
  {
    id: 'off-01',
    code: 'UVFLY10',
    title: 'Flight fare boost',
    description: 'Demo discount on selected domestic flights — mock only.',
    discountLabel: '10% off',
    validTill: '2026-09-30',
    category: 'Flights',
  },
  {
    id: 'off-02',
    code: 'STAY15',
    title: 'Hotel stay saver',
    description: 'Apply at mock checkout on 2+ night hotel bookings.',
    discountLabel: '15% off',
    validTill: '2026-08-31',
    category: 'Hotels',
  },
  {
    id: 'off-03',
    code: 'PACK5K',
    title: 'Holiday package credit',
    description: 'Flat mock credit on packages above ₹40,000.',
    discountLabel: '₹5,000 off',
    validTill: '2026-12-15',
    category: 'Packages',
  },
  {
    id: 'off-04',
    code: 'VISA99',
    title: 'Visa assist starter',
    description: 'Reduced mock service fee on first visa enquiry.',
    discountLabel: '₹99 fee',
    validTill: '2026-10-31',
    category: 'Visa',
  },
];

export const seedBookings: TravelBooking[] = [
  {
    id: 'bk-1001',
    category: 'flight',
    title: 'BOM → GOI · Demo Air DA 214',
    subtitle: '1 traveler · Economy',
    amount: 4899,
    status: 'confirmed',
    paymentStatus: 'paid',
    createdAt: '2026-07-10T09:20:00.000Z',
    travelDate: '2026-08-12',
    travelers: 1,
    reference: 'UV-FL-1001',
    details: { cabin: 'Economy', pnr: 'DEMO12' },
  },
  {
    id: 'bk-1002',
    category: 'hotel',
    title: 'Harbor View Demo Hotel',
    subtitle: 'Goa · 2 nights · Deluxe Twin',
    amount: 8400,
    status: 'confirmed',
    paymentStatus: 'paid',
    createdAt: '2026-07-12T14:05:00.000Z',
    travelDate: '2026-08-12',
    travelers: 2,
    reference: 'UV-HT-1002',
    details: { room: 'Deluxe Twin', checkIn: '2026-08-12', checkOut: '2026-08-14' },
  },
  {
    id: 'bk-1003',
    category: 'package',
    title: 'Dubai City Lights',
    subtitle: '4N/5D · 2 travelers',
    amount: 109998,
    status: 'pending',
    paymentStatus: 'partial',
    createdAt: '2026-07-18T11:40:00.000Z',
    travelDate: '2026-09-05',
    travelers: 2,
    reference: 'UV-PK-1003',
    details: { packageId: 'pkg-int-01', paid: '50000' },
  },
];

export const seedWalletTxns: WalletTxn[] = [
  {
    id: 'w-1',
    label: 'Welcome demo credit',
    amount: 2500,
    type: 'credit',
    at: '2026-07-01T10:00:00.000Z',
  },
  {
    id: 'w-2',
    label: 'Flight booking UV-FL-1001',
    amount: 4899,
    type: 'debit',
    at: '2026-07-10T09:21:00.000Z',
  },
  {
    id: 'w-3',
    label: 'Offer cashback (mock)',
    amount: 400,
    type: 'credit',
    at: '2026-07-11T08:00:00.000Z',
  },
];

export const seedWalletBalance = 5001;

export const adminCustomers = [
  { id: 'c-01', name: 'Demo Traveler', email: 'traveler@uandv.com', bookings: 3, spend: 123297 },
  { id: 'c-02', name: 'Sample Guest A', email: 'guest.a@demo.uandv', bookings: 1, spend: 8400 },
  { id: 'c-03', name: 'Sample Guest B', email: 'guest.b@demo.uandv', bookings: 2, spend: 27450 },
];

export const agentRequests = [
  {
    id: 'req-01',
    customer: 'Sample Guest A',
    type: 'Package',
    summary: 'Bali honeymoon · Sep dates',
    status: 'open',
    commission: 4200,
  },
  {
    id: 'req-02',
    customer: 'Sample Guest B',
    type: 'Flight + Hotel',
    summary: 'DEL→DXB with marina stay',
    status: 'quoted',
    commission: 3100,
  },
  {
    id: 'req-03',
    customer: 'Demo Traveler',
    type: 'Visa',
    summary: 'Schengen assist checklist',
    status: 'in_review',
    commission: 900,
  },
];

export const revenueTrend = [
  { label: 'Feb', value: 12 },
  { label: 'Mar', value: 15 },
  { label: 'Apr', value: 18 },
  { label: 'May', value: 21 },
  { label: 'Jun', value: 19 },
  { label: 'Jul', value: 24 },
];

export const categoryMix = [
  { label: 'Flights', value: 34 },
  { label: 'Hotels', value: 28 },
  { label: 'Packages', value: 22 },
  { label: 'Other', value: 16 },
];

export const visaCountries = [
  'United Arab Emirates',
  'Singapore',
  'Thailand',
  'Schengen (demo)',
  'United Kingdom',
  'United States',
];

export const insurancePlans = [
  {
    id: 'ins-01',
    name: 'Domestic Trip Cover',
    price: 299,
    cover: '₹2L medical · baggage delay',
  },
  {
    id: 'ins-02',
    name: 'International Standard',
    price: 1299,
    cover: '₹50L medical · trip delay',
  },
  {
    id: 'ins-03',
    name: 'Adventure Add-on',
    price: 899,
    cover: 'Activity cover · evacuation assist',
  },
];

export const carRentals = [
  {
    id: 'car-01',
    name: 'Compact Hatch',
    seats: 4,
    pricePerDay: 1800,
    features: ['AC', 'Manual', 'Unlimited km (demo)'],
  },
  {
    id: 'car-02',
    name: 'SUV Comfort',
    seats: 6,
    pricePerDay: 3200,
    features: ['AC', 'Automatic', 'Luggage space'],
  },
  {
    id: 'car-03',
    name: 'Premium Sedan',
    seats: 4,
    pricePerDay: 4500,
    features: ['Chauffeur option', 'AC', 'Airport ready'],
  },
];

export const sightseeingTours = [
  {
    id: 'ss-01',
    city: 'Goa',
    name: 'North Goa Highlights',
    duration: '6 hours',
    price: 1499,
    rating: 4.5,
  },
  {
    id: 'ss-02',
    city: 'Dubai',
    name: 'Skyline & Fountain Evening',
    duration: '4 hours',
    price: 3900,
    rating: 4.7,
  },
  {
    id: 'ss-03',
    city: 'Jaipur',
    name: 'Forts & Bazaars Walk',
    duration: '5 hours',
    price: 1200,
    rating: 4.6,
  },
  {
    id: 'ss-04',
    city: 'Singapore',
    name: 'Gardens & Marina Circuit',
    duration: '5 hours',
    price: 4200,
    rating: 4.8,
  },
];
