import { Badge, type BadgeProps } from '@uandv/ui';

const statusVariantMap: Record<string, BadgeProps['variant']> = {
  draft: 'secondary',
  active: 'info',
  on_hold: 'warning',
  completed: 'success',
  cancelled: 'error',
  submitted: 'secondary',
  in_review: 'info',
  quoted: 'warning',
  approved: 'success',
  closed: 'secondary',
  pending_signature: 'warning',
  signed: 'success',
  expired: 'error',
  renewal_due: 'warning',
  paid: 'success',
  pending: 'warning',
  overdue: 'error',
  upcoming: 'info',
  failed: 'error',
  open: 'info',
  in_progress: 'info',
  waiting: 'warning',
  resolved: 'success',
  low: 'secondary',
  medium: 'info',
  high: 'warning',
  urgent: 'error',
  not_applicable: 'secondary',
  secure_vault: 'success',
  pending_setup: 'warning',
  blocked: 'error',
  healthy: 'success',
  due_soon: 'warning',
  at_risk: 'error',
  reminded: 'info',
  onboarding: 'info',
  inactive: 'secondary',
  invited: 'warning',
  sent: 'info',
  scheduled: 'warning',
  none: 'secondary',
  new: 'info',
  contacted: 'secondary',
  interested: 'info',
  meeting: 'warning',
  proposal: 'default',
  negotiation: 'warning',
  won: 'success',
  customer: 'success',
  lost: 'error',
  meeting_scheduled: 'warning',
  proposal_sent: 'default',
  follow_up_later: 'secondary',
  website: 'secondary',
  whatsapp: 'success',
  referral: 'info',
  campaign: 'default',
  walk_in: 'secondary',
  other: 'secondary',
  call: 'info',
  email: 'secondary',
  note: 'secondary',
  follow_up: 'info',
  stage_change: 'warning',
  discovery: 'info',
  proposal_review: 'default',
  new_assignment: 'info',
  follow_up_due: 'warning',
  follow_up_overdue: 'error',
  meeting_reminder: 'info',
  admin_comment: 'secondary',
  lead_reassigned: 'warning',
  assigned: 'info',
  awaiting_review: 'warning',
  revision_requested: 'warning',
  revision_required: 'warning',
  rejected: 'error',
  processing: 'info',
  missing: 'secondary',
  verified: 'success',
  expiring_soon: 'warning',
  admin_message: 'info',
  internal_note: 'secondary',
  clarification: 'warning',
  revision_feedback: 'warning',
  meeting_summary: 'info',
  kickoff: 'info',
  review: 'warning',
  handover: 'success',
  deadline_reminder: 'warning',
  deliverable_review_completed: 'success',
  invoice_approved: 'success',
  payment_processed: 'success',
  document_expiry_reminder: 'warning',
  on_track: 'success',
  delayed: 'error',
  admin_only: 'error',
  internal_team: 'secondary',
  customer_visible: 'info',
  vendor_visible: 'warning',
  project_owner: 'info',
  internal_employee: 'secondary',
  vendor: 'warning',
  reviewer: 'info',
  approver: 'success',
  todo: 'secondary',
  mitigating: 'warning',
  accepted: 'secondary',
  critical: 'error',
  enquiry: 'secondary',
  requirement_discovery: 'info',
  advance_payment: 'warning',
  planning: 'info',
  design: 'info',
  development_execution: 'info',
  internal_review: 'warning',
  customer_review: 'warning',
  revision: 'warning',
  testing_verification: 'info',
  final_approval: 'success',
  deployment_submission: 'info',
  training: 'info',
  support: 'info',
  renewal_amc: 'secondary',
  not_raised: 'secondary',
  not_required: 'secondary',
  requirement: 'info',
  content: 'info',
  payment: 'warning',
  final_delivery: 'success',
  change_request: 'warning',
  skipped: 'secondary',
  eligible: 'success',
  pending_review: 'warning',
  not_eligible: 'secondary',
  converted: 'success',
  reviewed: 'success',
  ready: 'info',
  partial: 'warning',
  pending_approval: 'warning',
  disputed: 'error',
  queued: 'info',
  suspended: 'error',
  available: 'success',
  limited: 'warning',
  unavailable: 'secondary',
  not_started: 'secondary',
};

function humanize(value: string): string {
  return value
    .split('_')
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(' ');
}

export type StatusBadgeProps = {
  status: string;
  label?: string;
};

/** Accessible status chip for tables and cards. */
export function StatusBadge({ status, label }: StatusBadgeProps) {
  const text = label ?? humanize(status);
  return (
    <Badge variant={statusVariantMap[status] ?? 'secondary'}>
      <span className="sr-only">Status: </span>
      {text}
    </Badge>
  );
}
