import type { DiscoveryCopy } from '../types';

export const enDiscovery: DiscoveryCopy = {
  language: 'en',
  sectionBadge: 'A conversation with U&V',
  bridgeTitle: "Let's understand your business first.",
  bridgeBody: [
    'Every successful business begins with understanding.',
    "I'll ask only a few simple questions.",
    'No pressure.',
    'No technical jargon.',
    'No commitment.',
    'Just a conversation.',
  ].join('\n'),
  startCta: "Let's Get Started",
  progressBeginLabel: "Let's Begin",
  progressConversationLabel: 'Conversation {current} of {total}',
  progressCompleteLabel: 'Getting to Know You',
  backLabel: 'Go back',
  skipBudgetLabel: 'Skip for now — no pressure',
  continueLabel: 'Continue',
  summaryEyebrow: 'What I’m hearing',
  summaryTitle: 'Here’s a clear picture of your business so far',
  labelYourBusiness: 'Your Business',
  labelCurrentStage: 'Where You Are',
  labelMainGoal: 'What Matters Most',
  labelBiggestChallenge: 'What’s Holding You Back',
  labelPreferredStart: 'When You’re Ready',
  labelBudget: 'Comfortable Investment Range',
  labelRecommendedServices: 'Recommended next steps for your growth',
  labelEstimatedTimeline: 'Suggested Journey Timeline',
  labelBusinessReadiness: 'Business Readiness',
  timelineDays: '{days} Days',
  disclaimer:
    'This is an initial recommendation based on our conversation. Our U&V experts will prepare a personalized growth strategy after understanding your complete business.',
  ctaDownloadRoadmap: 'Download Your Growth Roadmap',
  ctaBookSession: 'Book a Free Strategy Conversation',
  ctaWhatsApp: 'Discuss on WhatsApp',
  ctaEmailReport: 'Email This Summary',
  restartLabel: 'Start this conversation again',
  changeAnswerHint:
    'You can go back anytime. This is a conversation — not a form, not a survey, not a test.',
  reassuranceMessages: [
    'Great.',
    'Thanks for sharing.',
    'Perfect. That helps me understand your business better.',
    'Excellent. Let’s move to the next step.',
    'Got it — thank you.',
    'That gives me a clearer picture.',
  ],
  questions: {
    industry: {
      prompt: 'What kind of business are we talking about?',
      helper: 'Choose the closest fit. We’ll refine the details together later.',
    },
    stage: {
      prompt: 'Where is your business today?',
      helper: 'There’s no right or wrong answer — I just want to meet you where you are.',
    },
    challenge: {
      prompt: 'What’s the biggest challenge on your mind right now?',
      helper: 'Pick the one that feels most important today.',
    },
    goal: {
      prompt: 'What would a good next chapter look like for you?',
      helper: 'This helps me guide you toward the right growth path.',
    },
    timeline: {
      prompt: 'When would you like to take the next step?',
      helper: 'Be honest — a realistic pace helps us support you better.',
    },
    budget: {
      prompt: 'What investment range feels comfortable for now?',
      helper: 'Optional. Skip if you’re not ready — no pressure at all.',
    },
  },
  options: {
    'industry.restaurant': 'Restaurant',
    'industry.hotel': 'Hotel',
    'industry.retail': 'Retail',
    'industry.supermarket': 'Supermarket',
    'industry.healthcare': 'Healthcare',
    'industry.education': 'Education',
    'industry.manufacturing': 'Manufacturing',
    'industry.travel': 'Travel',
    'industry.finance': 'Finance',
    'industry.real-estate': 'Real Estate',
    'industry.technology': 'Technology',
    'industry.other': 'Other',
    'stage.business-idea': 'Business Idea',
    'stage.startup': 'Startup',
    'stage.growing-business': 'Growing Business',
    'stage.established-business': 'Established Business',
    'stage.enterprise': 'Enterprise',
    'challenge.getting-more-customers': 'Getting More Customers',
    'challenge.website': 'Website',
    'challenge.mobile-app': 'Mobile App',
    'challenge.branding': 'Branding',
    'challenge.digital-marketing': 'Digital Marketing',
    'challenge.automation': 'Automation',
    'challenge.ai': 'AI',
    'challenge.managing-operations': 'Managing Operations',
    'challenge.complete-business-solution': 'Complete Growth Support',
    'goal.increase-revenue': 'Increase Revenue',
    'goal.save-time': 'Save Time',
    'goal.reduce-costs': 'Reduce Costs',
    'goal.expand-business': 'Expand Business',
    'goal.launch-faster': 'Launch Faster',
    'goal.digital-transformation': 'Digital Transformation',
    'timeline.immediately': 'Immediately',
    'timeline.within-30-days': 'Within 30 Days',
    'timeline.within-3-months': 'Within 3 Months',
    'timeline.research-phase': 'Still Exploring',
    'budget.25k-50k': '25K–50K',
    'budget.50k-1l': '50K–1L',
    'budget.1l-5l': '1L–5L',
    'budget.5l-plus': '5L+',
    'budget.not-sure': 'Not Sure Yet',
  },
  serviceLabels: {
    'company-registration': 'Company Registration',
    branding: 'Branding',
    website: 'Website',
    'mobile-app': 'Mobile App',
    'restaurant-pos': 'Restaurant Operations System',
    'hotel-management': 'Hotel Operations System',
    ecommerce: 'Online Store',
    crm: 'Customer Relationship System',
    erp: 'Business Operations System',
    'digital-marketing': 'Digital Marketing',
    'ai-automation': 'AI Automation',
    'custom-software': 'Custom Business Systems',
    'mlm-software': 'Network Business Platform',
    'business-consulting': 'Business Growth Guidance',
    'startup-support': 'Startup Support',
  },
};
