import type { DiscoveryCopy } from '../types';

export const enDiscovery: DiscoveryCopy = {
  language: 'en',
  bridgeTitle: 'Before I recommend anything…',
  bridgeBody:
    'I’d like to understand your business the way a consultant would in a first conversation — industry, stage, challenges, and goals. No personal details yet. Just clarity.',
  startCta: 'Start Business Discovery',
  progressLabel: 'Step {current} of {total}',
  backLabel: 'Back',
  skipBudgetLabel: 'Skip for now',
  continueLabel: 'Continue',
  summaryEyebrow: 'Your Business Summary',
  summaryTitle: 'Here’s what I’m hearing so far',
  labelYourBusiness: 'Your Business',
  labelCurrentStage: 'Current Stage',
  labelMainGoal: 'Main Goal',
  labelBiggestChallenge: 'Biggest Challenge',
  labelPreferredStart: 'Preferred Start',
  labelBudget: 'Estimated Budget',
  labelRecommendedServices: 'Recommended U&V Services',
  labelEstimatedTimeline: 'Estimated Timeline',
  labelBusinessReadiness: 'Business Readiness',
  timelineDays: '{days} Days',
  disclaimer:
    'This is an initial recommendation based on your answers. Our U&V experts will prepare a personalized strategy after understanding your complete business.',
  ctaDownloadRoadmap: 'Download Business Roadmap',
  ctaBookSession: 'Book Free Strategy Session',
  ctaWhatsApp: 'Discuss on WhatsApp',
  ctaEmailReport: 'Email This Report',
  restartLabel: 'Start over',
  changeAnswerHint: 'You can go back anytime — this is a conversation, not a test.',
  questions: {
    industry: {
      prompt: 'Which industry best describes your business?',
      helper: 'Pick the closest fit. We’ll refine the details together later.',
    },
    stage: {
      prompt: 'Which stage are you currently in?',
      helper: 'There’s no “right” answer — this just helps me meet you where you are.',
    },
    challenge: {
      prompt: 'What is your biggest challenge today?',
      helper: 'Choose the one that feels most urgent right now.',
    },
    goal: {
      prompt: 'What is your primary goal?',
      helper: 'This becomes the north star for your recommendation.',
    },
    timeline: {
      prompt: 'When would you like to start?',
      helper: 'Honesty helps us plan a realistic path with you.',
    },
    budget: {
      prompt: 'What is your estimated budget?',
      helper: 'Optional. Skip if you’re not ready — no pressure at all.',
    },
  },
  options: {
    'industry.restaurant': 'Restaurant',
    'industry.hotel': 'Hotel',
    'industry.retail': 'Retail',
    'industry.supermarket': 'Supermarket',
    'industry.healthcare': 'Healthcare',
    'industry.education': 'Education',
    'industry.manufacturing': 'Manufacturing',
    'industry.travel': 'Travel',
    'industry.finance': 'Finance',
    'industry.real-estate': 'Real Estate',
    'industry.technology': 'Technology',
    'industry.other': 'Other',
    'stage.business-idea': 'Business Idea',
    'stage.startup': 'Startup',
    'stage.growing-business': 'Growing Business',
    'stage.established-business': 'Established Business',
    'stage.enterprise': 'Enterprise',
    'challenge.getting-more-customers': 'Getting More Customers',
    'challenge.website': 'Website',
    'challenge.mobile-app': 'Mobile App',
    'challenge.branding': 'Branding',
    'challenge.digital-marketing': 'Digital Marketing',
    'challenge.automation': 'Automation',
    'challenge.ai': 'AI',
    'challenge.managing-operations': 'Managing Operations',
    'challenge.complete-business-solution': 'Complete Business Solution',
    'goal.increase-revenue': 'Increase Revenue',
    'goal.save-time': 'Save Time',
    'goal.reduce-costs': 'Reduce Costs',
    'goal.expand-business': 'Expand Business',
    'goal.launch-faster': 'Launch Faster',
    'goal.digital-transformation': 'Digital Transformation',
    'timeline.immediately': 'Immediately',
    'timeline.within-30-days': 'Within 30 Days',
    'timeline.within-3-months': 'Within 3 Months',
    'timeline.research-phase': 'Research Phase',
    'budget.25k-50k': '25K–50K',
    'budget.50k-1l': '50K–1L',
    'budget.1l-5l': '1L–5L',
    'budget.5l-plus': '5L+',
    'budget.not-sure': 'Not Sure Yet',
  },
  serviceLabels: {
    'company-registration': 'Company Registration',
    branding: 'Branding',
    website: 'Website',
    'mobile-app': 'Mobile App',
    'restaurant-pos': 'Restaurant POS',
    'hotel-management': 'Hotel Management System',
    ecommerce: 'E-commerce Platform',
    crm: 'CRM Software',
    erp: 'ERP Software',
    'digital-marketing': 'Digital Marketing',
    'ai-automation': 'AI Automation',
    'custom-software': 'Custom Software',
    'mlm-software': 'MLM Software',
    'business-consulting': 'Business Consulting',
    'startup-support': 'Startup Support',
  },
};
