/**
 * Seed service requests for Smart Matching demo — Sprint 3.2.
 */

import { matchPartnersForRequest } from './matching';
import type { ServiceRequest, ServiceRequestEvent } from './types';

function withMatches(
  base: Omit<
    ServiceRequest,
    'recommendedPartnerIds' | 'matchResults'
  > & {
    recommendedPartnerIds?: string[];
    matchResults?: ServiceRequest['matchResults'];
  },
): ServiceRequest {
  const matches =
    base.matchResults ??
    matchPartnersForRequest({
      partnerCategory: base.partnerCategory,
      city: base.city,
      state: base.state,
      budgetMinInr: base.budgetMinInr,
      budgetMaxInr: base.budgetMaxInr,
      timelineDays: base.timelineDays,
      estimatedPriceInr: base.estimatedPriceInr,
    });
  return {
    ...base,
    matchResults: matches,
    recommendedPartnerIds:
      base.recommendedPartnerIds ?? matches.map((m) => m.partnerId),
  };
}

export const demoServiceMarketplaceRequests: ServiceRequest[] = [
  withMatches({
    id: 'sreq-101',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    businessCategory: 'Retail',
    partnerCategory: 'gst_consultant',
    requestedService: 'GST Registration',
    city: 'Chennai',
    state: 'Tamil Nadu',
    budgetMinInr: 3000,
    budgetMaxInr: 8000,
    timelineDays: 14,
    requiredDocuments: ['PAN', 'Aadhaar', 'Business address proof', 'Bank proof'],
    priority: 'high',
    status: 'in_progress',
    source: 'marketplace',
    createdAt: '2026-07-02',
    marketplaceServiceId: 'svc-mkt-02',
    projectId: 'prj-204',
    assignedPartnerId: 'ptn-002',
    assignedPartnerName: 'TaxBridge GST Desk',
    vendorId: null,
    internalNotes: 'Linked to Sunrise compliance follow-up.',
    slaHours: 24,
    expectedCompletionDate: '2026-07-20',
    partnerResponseNote: 'Documents received — filing in progress.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 4999,
    estimatedDurationDays: 10,
  }),
  withMatches({
    id: 'sreq-102',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    businessCategory: 'Food & Agri',
    partnerCategory: 'company_registration',
    requestedService: 'Private Limited Company Registration',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    budgetMinInr: 10000,
    budgetMaxInr: 20000,
    timelineDays: 21,
    requiredDocuments: ['PAN', 'Aadhaar', 'Address proof', 'Photo'],
    priority: 'medium',
    status: 'partner_accepted',
    source: 'discovery',
    createdAt: '2026-07-05',
    marketplaceServiceId: 'svc-mkt-01',
    projectId: 'prj-311',
    assignedPartnerId: 'ptn-001',
    assignedPartnerName: 'LexStart Registrations',
    vendorId: null,
    internalNotes: 'Name approval pending.',
    slaHours: 36,
    expectedCompletionDate: '2026-07-28',
    partnerResponseNote: 'Accepted — DSC appointment booked.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 14999,
    estimatedDurationDays: 14,
  }),
  withMatches({
    id: 'sreq-103',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    businessCategory: 'Healthcare',
    partnerCategory: 'trademark_consultant',
    requestedService: 'Trademark Filing',
    city: 'Kochi',
    state: 'Kerala',
    budgetMinInr: 6000,
    budgetMaxInr: 12000,
    timelineDays: 30,
    requiredDocuments: ['Brand name/logo', 'Applicant ID'],
    priority: 'medium',
    status: 'assigned',
    source: 'marketplace',
    createdAt: '2026-07-08',
    marketplaceServiceId: 'svc-mkt-03',
    projectId: 'prj-088',
    assignedPartnerId: 'ptn-005',
    assignedPartnerName: 'MarkShield IP',
    vendorId: null,
    internalNotes: 'Class 44 preferred.',
    slaHours: 48,
    expectedCompletionDate: '2026-08-05',
    partnerResponseNote: null,
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 8999,
    estimatedDurationDays: 21,
  }),
  withMatches({
    id: 'sreq-104',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    businessCategory: 'Retail',
    partnerCategory: 'loan_consultant',
    requestedService: 'Loan Consultation — Working Capital',
    city: 'Chennai',
    state: 'Tamil Nadu',
    budgetMinInr: 5000,
    budgetMaxInr: 15000,
    timelineDays: 20,
    requiredDocuments: ['Financial statements', 'Bank statements', 'GST returns'],
    priority: 'urgent',
    status: 'recommended',
    source: 'advisor',
    createdAt: '2026-07-12',
    marketplaceServiceId: null,
    projectId: 'prj-204',
    assignedPartnerId: null,
    assignedPartnerName: null,
    vendorId: null,
    internalNotes: 'Awaiting admin assign from match shortlist.',
    slaHours: null,
    expectedCompletionDate: null,
    partnerResponseNote: null,
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 9999,
    estimatedDurationDays: 15,
  }),
  withMatches({
    id: 'sreq-105',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    businessCategory: 'Food & Agri',
    partnerCategory: 'investor_network',
    requestedService: 'Investor Readiness Package',
    city: 'Bengaluru',
    state: 'Karnataka',
    budgetMinInr: 25000,
    budgetMaxInr: 60000,
    timelineDays: 45,
    requiredDocuments: ['Pitch deck', 'Cap table', 'Financial model'],
    priority: 'high',
    status: 'new',
    source: 'dashboard',
    createdAt: '2026-07-14',
    marketplaceServiceId: null,
    projectId: null,
    assignedPartnerId: null,
    assignedPartnerName: null,
    vendorId: null,
    internalNotes: '',
    slaHours: null,
    expectedCompletionDate: null,
    partnerResponseNote: null,
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 45000,
    estimatedDurationDays: 30,
  }),
  withMatches({
    id: 'sreq-106',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    businessCategory: 'Retail',
    partnerCategory: 'graphic_design',
    requestedService: 'Logo and Branding Kit',
    city: 'Chennai',
    state: 'Tamil Nadu',
    budgetMinInr: 15000,
    budgetMaxInr: 40000,
    timelineDays: 21,
    requiredDocuments: ['Brand brief', 'Competitor references'],
    priority: 'high',
    status: 'partner_accepted',
    source: 'marketplace',
    createdAt: '2026-06-20',
    marketplaceServiceId: null,
    projectId: 'prj-204',
    assignedPartnerId: 'ptn-008',
    assignedPartnerName: 'Karthik Design Studio',
    vendorId: 'ven-001',
    internalNotes: 'Aligned with website redesign creative track.',
    slaHours: 36,
    expectedCompletionDate: '2026-07-25',
    partnerResponseNote: 'Moodboards shared — awaiting feedback.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 28000,
    estimatedDurationDays: 18,
  }),
  withMatches({
    id: 'sreq-107',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    businessCategory: 'Healthcare',
    partnerCategory: 'website_development',
    requestedService: 'Business Website Development',
    city: 'Kochi',
    state: 'Kerala',
    budgetMinInr: 50000,
    budgetMaxInr: 90000,
    timelineDays: 45,
    requiredDocuments: ['Brand kit', 'Content brief', 'Domain access'],
    priority: 'medium',
    status: 'awaiting_customer',
    source: 'marketplace',
    createdAt: '2026-06-28',
    marketplaceServiceId: 'svc-mkt-04',
    projectId: 'prj-088',
    assignedPartnerId: 'ptn-009',
    assignedPartnerName: 'PixelForge Labs',
    vendorId: null,
    internalNotes: 'Homepage draft waiting on content approval.',
    slaHours: 24,
    expectedCompletionDate: '2026-08-10',
    partnerResponseNote: 'Need final clinic photos.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 75000,
    estimatedDurationDays: 45,
  }),
  withMatches({
    id: 'sreq-108',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    businessCategory: 'Food & Agri',
    partnerCategory: 'mobile_app_development',
    requestedService: 'Mobile App Development',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    budgetMinInr: 150000,
    budgetMaxInr: 350000,
    timelineDays: 90,
    requiredDocuments: ['Product brief', 'User journeys', 'API notes'],
    priority: 'high',
    status: 'recommended',
    source: 'advisor',
    createdAt: '2026-07-15',
    marketplaceServiceId: null,
    projectId: null,
    assignedPartnerId: null,
    assignedPartnerName: null,
    vendorId: null,
    internalNotes: 'Match shortlist ready for admin.',
    slaHours: null,
    expectedCompletionDate: null,
    partnerResponseNote: null,
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 220000,
    estimatedDurationDays: 75,
  }),
  withMatches({
    id: 'sreq-109',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    businessCategory: 'Retail',
    partnerCategory: 'digital_marketing',
    requestedService: 'Digital Marketing Retainer',
    city: 'Chennai',
    state: 'Tamil Nadu',
    budgetMinInr: 20000,
    budgetMaxInr: 50000,
    timelineDays: 60,
    requiredDocuments: ['Brand assets', 'Target audience notes'],
    priority: 'medium',
    status: 'delivered',
    source: 'dashboard',
    createdAt: '2026-05-10',
    marketplaceServiceId: null,
    projectId: 'prj-204',
    assignedPartnerId: 'ptn-006',
    assignedPartnerName: 'Pulse Growth Studio',
    vendorId: null,
    internalNotes: 'Campaign report delivered.',
    slaHours: 24,
    expectedCompletionDate: '2026-07-10',
    partnerResponseNote: 'July report uploaded.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 35000,
    estimatedDurationDays: 30,
  }),
  withMatches({
    id: 'sreq-110',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    businessCategory: 'Healthcare',
    partnerCategory: 'printing',
    requestedService: 'Clinic Print Collateral',
    city: 'Kochi',
    state: 'Kerala',
    budgetMinInr: 8000,
    budgetMaxInr: 18000,
    timelineDays: 14,
    requiredDocuments: ['Print-ready artwork', 'Quantity list'],
    priority: 'low',
    status: 'completed',
    source: 'marketplace',
    createdAt: '2026-04-12',
    marketplaceServiceId: null,
    projectId: 'prj-088',
    assignedPartnerId: 'ptn-016',
    assignedPartnerName: 'Ink & Form Press',
    vendorId: null,
    internalNotes: 'Delivered and closed.',
    slaHours: 48,
    expectedCompletionDate: '2026-04-28',
    partnerResponseNote: 'Shipment completed.',
    customerRating: 5,
    customerRatingNote: 'Print quality was excellent.',
    estimatedPriceInr: 12000,
    estimatedDurationDays: 10,
  }),
  withMatches({
    id: 'sreq-111',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    businessCategory: 'Food & Agri',
    partnerCategory: 'recruitment',
    requestedService: 'Recruitment — Operations Lead',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    budgetMinInr: 15000,
    budgetMaxInr: 40000,
    timelineDays: 35,
    requiredDocuments: ['JD', 'Salary band', 'Interview panel'],
    priority: 'medium',
    status: 'on_hold',
    source: 'admin',
    createdAt: '2026-07-01',
    marketplaceServiceId: null,
    projectId: null,
    assignedPartnerId: 'ptn-017',
    assignedPartnerName: 'HireSouth Talent',
    vendorId: null,
    internalNotes: 'On hold — JD revision pending from customer.',
    slaHours: 24,
    expectedCompletionDate: '2026-08-05',
    partnerResponseNote: 'Paused until JD is final.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 28000,
    estimatedDurationDays: 30,
  }),
  withMatches({
    id: 'sreq-112',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    businessCategory: 'Retail',
    partnerCategory: 'insurance',
    requestedService: 'Business Insurance Advisory',
    city: 'Madurai',
    state: 'Tamil Nadu',
    budgetMinInr: 5000,
    budgetMaxInr: 20000,
    timelineDays: 25,
    requiredDocuments: ['Business registration', 'Asset list'],
    priority: 'low',
    status: 'declined',
    source: 'dashboard',
    createdAt: '2026-06-15',
    marketplaceServiceId: null,
    projectId: null,
    assignedPartnerId: 'ptn-018',
    assignedPartnerName: 'ShieldPath Insurance Desk',
    vendorId: null,
    internalNotes: 'Partner declined — outside service area preference.',
    slaHours: 36,
    expectedCompletionDate: null,
    partnerResponseNote: 'Unable to cover Madurai field survey this quarter.',
    customerRating: null,
    customerRatingNote: null,
    estimatedPriceInr: 9999,
    estimatedDurationDays: 20,
  }),
];

export const demoServiceRequestEvents: ServiceRequestEvent[] = [
  {
    id: 'sre-101-1',
    requestId: 'sreq-101',
    occurredAt: '2026-07-02T10:00:00+05:30',
    title: 'Request created',
    description: 'GST Registration requested from marketplace.',
    actorRole: 'customer',
    actorName: 'Priya Sharma',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-101-2',
    requestId: 'sreq-101',
    occurredAt: '2026-07-02T10:05:00+05:30',
    title: 'Matching completed',
    description: 'Smart Matching shortlisted top partners (Demo Intelligence).',
    actorRole: 'system',
    actorName: 'Smart Matching',
    customerVisible: true,
    partnerVisible: false,
  },
  {
    id: 'sre-101-3',
    requestId: 'sreq-101',
    occurredAt: '2026-07-03T11:00:00+05:30',
    title: 'Partner assigned',
    description: 'TaxBridge GST Desk assigned by Admin.',
    actorRole: 'admin',
    actorName: 'Admin',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-101-4',
    requestId: 'sreq-101',
    occurredAt: '2026-07-03T15:20:00+05:30',
    title: 'Partner accepted',
    description: 'Partner accepted the opportunity.',
    actorRole: 'partner',
    actorName: 'TaxBridge GST Desk',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-101-5',
    requestId: 'sreq-101',
    occurredAt: '2026-07-04T09:00:00+05:30',
    title: 'Work started',
    description: 'Filing preparation started.',
    actorRole: 'partner',
    actorName: 'TaxBridge GST Desk',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-106-1',
    requestId: 'sreq-106',
    occurredAt: '2026-06-20T12:00:00+05:30',
    title: 'Request created',
    description: 'Logo and branding kit requested.',
    actorRole: 'customer',
    actorName: 'Priya Sharma',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-106-2',
    requestId: 'sreq-106',
    occurredAt: '2026-06-21T10:00:00+05:30',
    title: 'Partner assigned',
    description: 'Karthik Design Studio assigned (Vendor Workspace ven-001).',
    actorRole: 'admin',
    actorName: 'Admin',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-106-3',
    requestId: 'sreq-106',
    occurredAt: '2026-06-21T14:00:00+05:30',
    title: 'Partner accepted',
    description: 'Creative partner accepted branding scope.',
    actorRole: 'partner',
    actorName: 'Karthik Design Studio',
    customerVisible: true,
    partnerVisible: true,
  },
  {
    id: 'sre-110-1',
    requestId: 'sreq-110',
    occurredAt: '2026-04-28T16:00:00+05:30',
    title: 'Request completed',
    description: 'Customer approved deliverable and rated 5★.',
    actorRole: 'customer',
    actorName: 'Ananya Rao',
    customerVisible: true,
    partnerVisible: true,
  },
];
