/**
 * Lifecycle demo data — Sprint 3.2.
 * Lifetime business events + role notifications + happiness scores.
 * Project-linked timeline entries are also derived in the engine from ProjectActivity.
 */

import type {
  BusinessTimelineEvent,
  CustomerHappinessScore,
  LifecycleNotification,
} from './types';

export const demoBusinessTimelineEvents: BusinessTimelineEvent[] = [
  {
    id: 'blt-001',
    occurredAt: '2025-11-02T11:00:00+05:30',
    kind: 'account',
    title: 'Customer account created',
    description: 'Sunrise Retail onboarded to U&V Business Workspace.',
    actorName: 'System',
    actorRole: 'system',
    visibility: 'customer_visible',
    projectId: null,
    projectTitle: null,
    relatedStage: null,
    customerId: 'cus-001',
    employeeId: null,
    vendorId: null,
  },
  {
    id: 'blt-002',
    occurredAt: '2025-11-08T15:30:00+05:30',
    kind: 'enquiry',
    title: 'Website redesign enquiry received',
    description: 'Initial scope discussion for marketing site rebuild.',
    actorName: 'Priya Sharma',
    actorRole: 'customer',
    visibility: 'customer_visible',
    projectId: null,
    projectTitle: null,
    relatedStage: 'enquiry',
    customerId: 'cus-001',
    employeeId: 'emp-001',
    vendorId: null,
  },
  {
    id: 'blt-003',
    occurredAt: '2025-12-01T10:00:00+05:30',
    kind: 'proposal',
    title: 'Proposal shared',
    description: 'Commercial proposal and delivery plan shared with customer.',
    actorName: 'Divya P.',
    actorRole: 'employee',
    visibility: 'customer_visible',
    projectId: null,
    projectTitle: null,
    relatedStage: 'proposal',
    customerId: 'cus-001',
    employeeId: 'emp-001',
    vendorId: null,
  },
  {
    id: 'blt-004',
    occurredAt: '2026-01-10T12:00:00+05:30',
    kind: 'agreement',
    title: 'Service agreement signed',
    description: 'Demo signature placeholder recorded for website engagement.',
    actorName: 'Priya Sharma',
    actorRole: 'customer',
    visibility: 'customer_visible',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    relatedStage: 'agreement',
    customerId: 'cus-001',
    employeeId: null,
    vendorId: null,
  },
  {
    id: 'blt-005',
    occurredAt: '2026-01-12T09:30:00+05:30',
    kind: 'payment',
    title: 'Advance payment recorded',
    description: 'Advance against website redesign project (demo ledger).',
    actorName: 'Arun Kumar',
    actorRole: 'admin',
    visibility: 'customer_visible',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    relatedStage: 'advance_payment',
    customerId: 'cus-001',
    employeeId: null,
    vendorId: null,
  },
  {
    id: 'blt-006',
    occurredAt: '2026-03-15T14:00:00+05:30',
    kind: 'assignment',
    title: 'Vendor assigned — UI kit',
    description: 'Karthik Design Studio assigned for homepage UI kit.',
    actorName: 'Arun Kumar',
    actorRole: 'admin',
    visibility: 'vendor_visible',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    relatedStage: 'design',
    customerId: 'cus-001',
    employeeId: null,
    vendorId: 'ven-001',
  },
  {
    id: 'blt-007',
    occurredAt: '2026-06-05T11:00:00+05:30',
    kind: 'project',
    title: 'GST registration project opened',
    description: 'GreenLeaf Organics compliance engagement started.',
    actorName: 'Meena R.',
    actorRole: 'employee',
    visibility: 'internal_team',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    relatedStage: 'enquiry',
    customerId: 'cus-002',
    employeeId: 'emp-002',
    vendorId: null,
  },
  {
    id: 'blt-008',
    occurredAt: '2026-07-10T16:00:00+05:30',
    kind: 'approval',
    title: 'Logo direction pending customer choice',
    description: 'Customer review requested for brand directions B and C.',
    actorName: 'Divya P.',
    actorRole: 'employee',
    visibility: 'customer_visible',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    relatedStage: 'customer_review',
    customerId: 'cus-003',
    employeeId: 'emp-001',
    vendorId: 'ven-001',
  },
  {
    id: 'blt-009',
    occurredAt: '2026-07-20T09:00:00+05:30',
    kind: 'review',
    title: 'Delivery health check',
    description: 'Admin reviewed delayed tasks and open risks across portfolio.',
    actorName: 'Arun Kumar',
    actorRole: 'admin',
    visibility: 'admin_only',
    projectId: null,
    projectTitle: null,
    relatedStage: null,
    customerId: null,
    employeeId: null,
    vendorId: null,
  },
  {
    id: 'blt-010',
    occurredAt: '2026-07-22T18:00:00+05:30',
    kind: 'support',
    title: 'Support touchpoint logged',
    description: 'Customer asked about CMS training schedule.',
    actorName: 'Priya Sharma',
    actorRole: 'customer',
    visibility: 'customer_visible',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    relatedStage: 'training',
    customerId: 'cus-001',
    employeeId: 'emp-001',
    vendorId: null,
  },
];

export const demoCustomerHappiness: CustomerHappinessScore[] = [
  {
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    overall: 82,
    trend: 'up',
    summary:
      'Strong communication and delivery transparency. Waiting on CMS training slot confirmation.',
    dimensions: [
      { key: 'communication', label: 'Communication', score: 88 },
      { key: 'delivery', label: 'Delivery pace', score: 78 },
      { key: 'quality', label: 'Quality perception', score: 85 },
      { key: 'support', label: 'Support response', score: 80 },
      { key: 'transparency', label: 'Transparency', score: 84 },
    ],
    drivers: [
      'Regular work updates on website redesign',
      'Clear payment milestones',
      'Pending training schedule slightly lowers score',
    ],
    disclaimer:
      'Customer Happiness Score is a demo composite — not a live survey engine.',
  },
  {
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    overall: 64,
    trend: 'down',
    summary: 'KYC clarification delay is impacting perceived progress.',
    dimensions: [
      { key: 'communication', label: 'Communication', score: 70 },
      { key: 'delivery', label: 'Delivery pace', score: 55 },
      { key: 'quality', label: 'Quality perception', score: 72 },
      { key: 'support', label: 'Support response', score: 68 },
      { key: 'transparency', label: 'Transparency', score: 60 },
    ],
    drivers: [
      'Document clarification pending',
      'Target date at risk',
    ],
    disclaimer:
      'Customer Happiness Score is a demo composite — not a live survey engine.',
  },
  {
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    overall: 71,
    trend: 'stable',
    summary: 'Brand directions awaiting selection — customer action required.',
    dimensions: [
      { key: 'communication', label: 'Communication', score: 76 },
      { key: 'delivery', label: 'Delivery pace', score: 65 },
      { key: 'quality', label: 'Quality perception', score: 80 },
      { key: 'support', label: 'Support response', score: 74 },
      { key: 'transparency', label: 'Transparency', score: 70 },
    ],
    drivers: [
      'Vendor pack delivered',
      'Approval delay on logo direction',
    ],
    disclaimer:
      'Customer Happiness Score is a demo composite — not a live survey engine.',
  },
];

export const demoLifecycleNotifications: LifecycleNotification[] = [
  {
    id: 'lcn-a1',
    role: 'admin',
    category: 'health',
    title: 'High-risk project needs attention',
    description: 'Coastal Dental brand refresh has a critical open risk.',
    createdAt: '2026-07-23T08:00:00+05:30',
    unread: true,
    projectId: 'prj-088',
    href: '/admin/projects/prj-088',
    employeeId: null,
    vendorId: null,
    customerId: 'cus-003',
  },
  {
    id: 'lcn-a2',
    role: 'admin',
    category: 'approval',
    title: 'Pending customer approvals',
    description: 'Multiple projects await customer decisions.',
    createdAt: '2026-07-22T17:00:00+05:30',
    unread: true,
    projectId: null,
    href: '/admin/projects',
    employeeId: null,
    vendorId: null,
    customerId: null,
  },
  {
    id: 'lcn-a3',
    role: 'admin',
    category: 'payment',
    title: 'Milestone payment pending',
    description: 'Website redesign has outstanding milestone amount.',
    createdAt: '2026-07-21T12:00:00+05:30',
    unread: false,
    projectId: 'prj-204',
    href: '/admin/projects/prj-204/payments',
    employeeId: null,
    vendorId: null,
    customerId: 'cus-001',
  },
  {
    id: 'lcn-c1',
    role: 'customer',
    category: 'project',
    title: 'Website redesign progress update',
    description: 'Templates are in progress — review upcoming training plan.',
    createdAt: '2026-07-22T16:00:00+05:30',
    unread: true,
    projectId: 'prj-204',
    href: '/dashboard/projects/prj-204',
    employeeId: null,
    vendorId: null,
    customerId: 'cus-001',
  },
  {
    id: 'lcn-c2',
    role: 'customer',
    category: 'approval',
    title: 'Action needed: content approval',
    description: 'Please approve homepage content draft when ready.',
    createdAt: '2026-07-21T10:00:00+05:30',
    unread: true,
    projectId: 'prj-204',
    href: '/dashboard/projects/prj-204/approvals',
    employeeId: null,
    vendorId: null,
    customerId: 'cus-001',
  },
  {
    id: 'lcn-c3',
    role: 'customer',
    category: 'payment',
    title: 'Payment reminder',
    description: 'Next milestone invoice is visible in your payments view.',
    createdAt: '2026-07-20T09:00:00+05:30',
    unread: false,
    projectId: 'prj-204',
    href: '/dashboard/projects/prj-204/payments',
    employeeId: null,
    vendorId: null,
    customerId: 'cus-001',
  },
  {
    id: 'lcn-e1',
    role: 'employee',
    category: 'assignment',
    title: 'Project task due today',
    description: 'Schedule CMS training with Sunrise Retail.',
    createdAt: '2026-07-23T07:30:00+05:30',
    unread: true,
    projectId: 'prj-204',
    href: '/employee/tasks',
    employeeId: 'emp-001',
    vendorId: null,
    customerId: 'cus-001',
  },
  {
    id: 'lcn-e2',
    role: 'employee',
    category: 'deadline',
    title: 'Follow up on brand approval',
    description: 'Coastal Dental logo direction still pending.',
    createdAt: '2026-07-22T11:00:00+05:30',
    unread: true,
    projectId: 'prj-088',
    href: '/employee/tasks',
    employeeId: 'emp-001',
    vendorId: null,
    customerId: 'cus-003',
  },
  {
    id: 'lcn-e3',
    role: 'employee',
    category: 'project',
    title: 'Internal note on templates',
    description: 'Align CMS templates with vendor UI kit tokens.',
    createdAt: '2026-07-21T15:00:00+05:30',
    unread: false,
    projectId: 'prj-204',
    href: '/employee/tasks',
    employeeId: 'emp-001',
    vendorId: null,
    customerId: null,
  },
  {
    id: 'lcn-v1',
    role: 'vendor',
    category: 'deadline',
    title: 'UI kit deadline approaching',
    description: 'Homepage UI kit delivery due 28 Jul.',
    createdAt: '2026-07-23T08:15:00+05:30',
    unread: true,
    projectId: 'prj-204',
    href: '/vendor/work',
    employeeId: null,
    vendorId: 'ven-001',
    customerId: null,
  },
  {
    id: 'lcn-v2',
    role: 'vendor',
    category: 'assignment',
    title: 'New work order linked',
    description: 'Brand pack task remains assigned from Admin.',
    createdAt: '2026-07-20T13:00:00+05:30',
    unread: true,
    projectId: 'prj-088',
    href: '/vendor/work',
    employeeId: null,
    vendorId: 'ven-001',
    customerId: null,
  },
  {
    id: 'lcn-v3',
    role: 'vendor',
    category: 'document',
    title: 'Revision feedback available',
    description: 'Check permitted project context for revision notes.',
    createdAt: '2026-07-19T16:30:00+05:30',
    unread: false,
    projectId: 'prj-088',
    href: '/vendor/deliverables',
    employeeId: null,
    vendorId: 'ven-001',
    customerId: null,
  },
];
