/**
 * Financial operations demo data — Sprint 3.3.
 * Linked to cus-001 / prj-204 / ven-001 shared models.
 */

import type {
  BusinessOpsSnapshot,
  FinanceAgreement,
  FinanceExpense,
  FinanceInvoice,
  FinancePaymentEntry,
  FinanceQuotation,
  ProfitSnapshot,
  VendorSettlement,
} from './types';

export const FINANCE_DEMO_TODAY = '2026-07-23';

export const demoQuotations: FinanceQuotation[] = [
  {
    id: 'quo-101',
    number: 'UV-Q-2026-014',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    title: 'Website redesign + CMS training',
    amountInr: 420000,
    status: 'converted',
    issuedAt: '2025-12-01',
    validUntil: '2026-01-15',
    ownerName: 'Divya P.',
    notes: 'Converted to agreement agr-fin-501',
  },
  {
    id: 'quo-102',
    number: 'UV-Q-2026-031',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: null,
    projectTitle: null,
    title: 'SEO retainer — 3 months',
    amountInr: 75000,
    status: 'sent',
    issuedAt: '2026-07-10',
    validUntil: '2026-08-10',
    ownerName: 'Divya P.',
    notes: 'Awaiting customer decision',
  },
  {
    id: 'quo-103',
    number: 'UV-Q-2026-028',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    title: 'GST registration package',
    amountInr: 18000,
    status: 'accepted',
    issuedAt: '2026-05-20',
    validUntil: '2026-06-20',
    ownerName: 'Meena R.',
    notes: 'Linked to compliance project',
  },
  {
    id: 'quo-104',
    number: 'UV-Q-2026-033',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    title: 'Brand refresh add-on — stationery pack',
    amountInr: 22000,
    status: 'draft',
    issuedAt: '2026-07-18',
    validUntil: '2026-08-18',
    ownerName: 'Divya P.',
    notes: 'Admin draft — not customer visible until sent',
  },
];

export const demoFinanceAgreements: FinanceAgreement[] = [
  {
    id: 'agr-fin-501',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    title: 'Website redesign master service agreement',
    status: 'signed',
    valueInr: 420000,
    signedAt: '2026-01-10',
    expiryOrRenewalAt: '2027-01-10',
    auditLabel: 'Demo audit · SHA placeholder',
  },
  {
    id: 'agr-fin-502',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: null,
    projectTitle: null,
    title: 'Hosting & support AMC',
    status: 'renewal_due',
    valueInr: 48000,
    signedAt: '2025-08-01',
    expiryOrRenewalAt: '2026-08-01',
    auditLabel: 'Demo audit · renewal window open',
  },
  {
    id: 'agr-fin-503',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    title: 'GST registration engagement letter',
    status: 'signed',
    valueInr: 18000,
    signedAt: '2026-06-01',
    expiryOrRenewalAt: '2026-12-01',
    auditLabel: 'Demo audit · compliance scope',
  },
  {
    id: 'agr-fin-504',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    title: 'Brand refresh statement of work',
    status: 'pending_signature',
    valueInr: 65000,
    signedAt: null,
    expiryOrRenewalAt: '2026-08-15',
    auditLabel: 'Demo audit · awaiting signature',
  },
];

export const demoFinanceInvoices: FinanceInvoice[] = [
  {
    id: 'fin-inv-901',
    number: 'UV-INV-2026-0210',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    amountInr: 120000,
    paidAmountInr: 120000,
    status: 'paid',
    dueDate: '2026-01-20',
    issuedAt: '2026-01-12',
    reminderStatus: 'none',
  },
  {
    id: 'fin-inv-902',
    number: 'UV-INV-2026-0288',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    amountInr: 150000,
    paidAmountInr: 0,
    status: 'pending',
    dueDate: '2026-07-30',
    issuedAt: '2026-07-05',
    reminderStatus: 'sent',
  },
  {
    id: 'fin-inv-903',
    number: 'UV-INV-2026-0301',
    customerId: 'cus-002',
    customerName: 'Karthik Nair',
    customerBusinessName: 'GreenLeaf Organics',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    amountInr: 9000,
    paidAmountInr: 9000,
    status: 'paid',
    dueDate: '2026-06-10',
    issuedAt: '2026-06-02',
    reminderStatus: 'none',
  },
  {
    id: 'fin-inv-904',
    number: 'UV-INV-2026-0315',
    customerId: 'cus-003',
    customerName: 'Ananya Rao',
    customerBusinessName: 'Coastal Dental',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    amountInr: 25000,
    paidAmountInr: 0,
    status: 'overdue',
    dueDate: '2026-07-15',
    issuedAt: '2026-07-01',
    reminderStatus: 'queued',
  },
  {
    id: 'fin-inv-905',
    number: 'UV-INV-2026-0320',
    customerId: 'cus-001',
    customerName: 'Priya Sharma',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    amountInr: 150000,
    paidAmountInr: 0,
    status: 'upcoming',
    dueDate: '2026-08-20',
    issuedAt: '2026-07-20',
    reminderStatus: 'none',
  },
];

export const demoPaymentTracker: FinancePaymentEntry[] = [
  {
    id: 'pay-tr-1',
    invoiceId: 'fin-inv-901',
    customerId: 'cus-001',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    label: 'Advance payment',
    amountInr: 120000,
    status: 'paid',
    dueDate: '2026-01-20',
    paidAt: '2026-01-15',
  },
  {
    id: 'pay-tr-2',
    invoiceId: 'fin-inv-902',
    customerId: 'cus-001',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    label: 'Milestone 2 — Design & templates',
    amountInr: 150000,
    status: 'pending',
    dueDate: '2026-07-30',
    paidAt: null,
  },
  {
    id: 'pay-tr-3',
    invoiceId: 'fin-inv-905',
    customerId: 'cus-001',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    label: 'Milestone 3 — Launch',
    amountInr: 150000,
    status: 'upcoming',
    dueDate: '2026-08-20',
    paidAt: null,
  },
  {
    id: 'pay-tr-4',
    invoiceId: 'fin-inv-903',
    customerId: 'cus-002',
    customerBusinessName: 'GreenLeaf Organics',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    label: 'GST package advance',
    amountInr: 9000,
    status: 'paid',
    dueDate: '2026-06-10',
    paidAt: '2026-06-08',
  },
  {
    id: 'pay-tr-5',
    invoiceId: 'fin-inv-904',
    customerId: 'cus-003',
    customerBusinessName: 'Coastal Dental',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    label: 'Brand refresh advance',
    amountInr: 25000,
    status: 'overdue',
    dueDate: '2026-07-15',
    paidAt: null,
  },
];

export const demoExpenses: FinanceExpense[] = [
  {
    id: 'exp-1',
    title: 'Vendor UI kit payment accrual',
    category: 'vendor_cost',
    amountInr: 45000,
    status: 'approved',
    incurredAt: '2026-07-12',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    vendorId: 'ven-001',
    vendorName: 'Karthik Design Studio',
    ownerName: 'Arun Kumar',
    notes: 'Linked to settlement set-101',
    adminOnly: true,
  },
  {
    id: 'exp-2',
    title: 'Figma organization seats',
    category: 'software',
    amountInr: 8200,
    status: 'paid',
    incurredAt: '2026-07-01',
    projectId: null,
    projectTitle: null,
    vendorId: null,
    vendorName: null,
    ownerName: 'Arun Kumar',
    notes: 'Monthly tools',
    adminOnly: true,
  },
  {
    id: 'exp-3',
    title: 'Client kickoff travel — Coimbatore',
    category: 'travel',
    amountInr: 6500,
    status: 'submitted',
    incurredAt: '2026-07-18',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    vendorId: null,
    vendorName: null,
    ownerName: 'Divya P.',
    notes: 'Pending admin approval',
    adminOnly: true,
  },
  {
    id: 'exp-4',
    title: 'Meta ads test budget',
    category: 'marketing',
    amountInr: 12000,
    status: 'paid',
    incurredAt: '2026-06-28',
    projectId: null,
    projectTitle: null,
    vendorId: null,
    vendorName: null,
    ownerName: 'Arun Kumar',
    notes: 'Lead gen experiment',
    adminOnly: true,
  },
  {
    id: 'exp-5',
    title: 'Compliance filing disbursement',
    category: 'operations',
    amountInr: 3500,
    status: 'approved',
    incurredAt: '2026-07-05',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    vendorId: null,
    vendorName: null,
    ownerName: 'Meena R.',
    notes: 'Govt fee placeholder',
    adminOnly: true,
  },
];

export const demoVendorSettlements: VendorSettlement[] = [
  {
    id: 'set-101',
    vendorId: 'ven-001',
    vendorName: 'Karthik Design Studio',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    workOrderLabel: 'Homepage UI kit delivery',
    amountInr: 45000,
    status: 'eligible',
    eligibleAt: '2026-07-20',
    paidAt: null,
    invoiceRef: 'VEN-INV-2026-014',
    adminNotes: 'Hold until mid-review sign-off',
    vendorVisibleNote: 'Eligible after Admin review of UI kit deliverable.',
  },
  {
    id: 'set-102',
    vendorId: 'ven-001',
    vendorName: 'Karthik Design Studio',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    workOrderLabel: 'Logo direction pack',
    amountInr: 18000,
    status: 'pending_approval',
    eligibleAt: '2026-07-22',
    paidAt: null,
    invoiceRef: 'VEN-INV-2026-018',
    adminNotes: 'Waiting on customer logo selection',
    vendorVisibleNote: 'Settlement pending Admin approval.',
  },
  {
    id: 'set-103',
    vendorId: 'ven-001',
    vendorName: 'Karthik Design Studio',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    workOrderLabel: 'Mobile breakpoint kit (phase 1)',
    amountInr: 22000,
    status: 'paid',
    eligibleAt: '2026-06-01',
    paidAt: '2026-06-15',
    invoiceRef: 'VEN-INV-2026-009',
    adminNotes: 'Paid via demo ledger',
    vendorVisibleNote: 'Paid on 15 Jun 2026 (demo).',
  },
  {
    id: 'set-104',
    vendorId: 'ven-002',
    vendorName: 'Nova Print Partners',
    projectId: null,
    projectTitle: null,
    workOrderLabel: 'Brochure print batch',
    amountInr: 9500,
    status: 'on_hold',
    eligibleAt: '2026-07-10',
    paidAt: null,
    invoiceRef: null,
    adminNotes: 'Different vendor — ven-001 must not see this row',
    vendorVisibleNote: 'On hold',
  },
];

export const demoProfitSnapshot: ProfitSnapshot = {
  periodLabel: 'Jul 2026 (MTD demo)',
  revenueInr: 304000,
  expensesInr: 75200,
  vendorSettlementsInr: 40000,
  grossProfitInr: 188800,
  marginPercent: 62,
  outstandingReceivablesInr: 325000,
  outstandingPayablesInr: 63000,
  disclaimer:
    'Profit figures are demo aggregates from quotations, invoices, expenses, and settlements. Not a live accounting engine.',
};

export const demoBusinessOpsSnapshot: BusinessOpsSnapshot = {
  activeQuotations: 2,
  pendingAgreements: 1,
  openInvoices: 3,
  overduePayments: 1,
  pendingExpenses: 1,
  pendingSettlements: 2,
  revenueMtdInr: 304000,
  profitMtdInr: 188800,
  topCustomers: [
    {
      customerId: 'cus-001',
      name: 'Sunrise Retail Pvt Ltd',
      revenueInr: 270000,
    },
    {
      customerId: 'cus-003',
      name: 'Coastal Dental',
      revenueInr: 25000,
    },
    {
      customerId: 'cus-002',
      name: 'GreenLeaf Organics',
      revenueInr: 9000,
    },
  ],
  alerts: [
    '1 overdue customer payment (Coastal Dental)',
    '2 vendor settlements awaiting approval/payment',
    '1 expense submitted for approval',
    'SEO retainer quotation awaiting customer response',
  ],
};
