/**
 * Partner Network & Marketplace demo data — Release 3.6.
 */

import type {
  BusinessServiceTemplate,
  MarketplaceService,
  Partner,
  PartnerAssignment,
  PartnerCommunication,
  PartnerDocument,
  PartnerPaymentSummary,
  PartnerPerformance,
} from './types';

export const PARTNER_DEMO_TODAY = '2026-07-23';

export const PARTNER_CATEGORY_LABELS: Record<
  Partner['category'],
  string
> = {
  company_registration: 'Company Registration',
  gst_consultant: 'GST Consultant',
  chartered_accountant: 'Chartered Accountant',
  lawyer: 'Lawyer',
  trademark_consultant: 'Trademark Consultant',
  digital_marketing: 'Digital Marketing',
  seo: 'SEO',
  graphic_design: 'Graphic Design',
  printing: 'Printing',
  website_development: 'Website Development',
  mobile_app_development: 'Mobile App Development',
  ai_automation: 'AI Automation',
  video_production: 'Video Production',
  cloud_services: 'Cloud Services',
  hosting: 'Hosting',
  hr_services: 'HR Services',
  recruitment: 'Recruitment',
  business_consultant: 'Business Consultant',
  loan_consultant: 'Loan Consultant',
  investor_network: 'Investor Network',
  insurance: 'Insurance',
  logistics: 'Logistics',
};

export const demoPartners: Partner[] = [
  {
    id: 'ptn-001',
    category: 'company_registration',
    companyName: 'LexStart Registrations',
    contactPerson: 'Anitha S.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    serviceArea: 'Tamil Nadu · PAN India filings',
    skills: ['Private Limited', 'LLP', 'OPC', 'DPIIT'],
    rating: 4.7,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 9,
    performanceScore: 88,
    commissionType: 'fixed',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Fast company incorporation and compliance kickoff partner.',
    slaHours: 24,
  },
  {
    id: 'ptn-002',
    category: 'gst_consultant',
    companyName: 'TaxBridge GST Desk',
    contactPerson: 'Vikram R.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    serviceArea: 'West Tamil Nadu',
    skills: ['GST registration', 'Returns', 'Notices'],
    rating: 4.5,
    verificationStatus: 'verified',
    availability: 'limited',
    experienceYears: 7,
    performanceScore: 82,
    commissionType: 'percent',
    documentsStatus: 'verified',
    bankVerificationStatus: 'pending',
    summary: 'GST registration and ongoing return support.',
    slaHours: 36,
  },
  {
    id: 'ptn-003',
    category: 'chartered_accountant',
    companyName: 'Nexus CA Associates',
    contactPerson: 'Meera K.',
    city: 'Bengaluru',
    state: 'Karnataka',
    serviceArea: 'South India',
    skills: ['Audit', 'Books', 'Tax planning'],
    rating: 4.8,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 12,
    performanceScore: 91,
    commissionType: 'retainer',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Accounting and statutory audit partner for SMEs.',
    slaHours: 48,
  },
  {
    id: 'ptn-004',
    category: 'lawyer',
    companyName: 'Harbor Legal Advisors',
    contactPerson: 'Suresh P.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    serviceArea: 'Tamil Nadu · remote consults',
    skills: ['Contracts', 'Employment', 'Disputes'],
    rating: 4.4,
    verificationStatus: 'pending',
    availability: 'available',
    experienceYears: 10,
    performanceScore: 76,
    commissionType: 'hybrid',
    documentsStatus: 'submitted',
    bankVerificationStatus: 'not_started',
    summary: 'Commercial contracts and legal opinion partner.',
    slaHours: 48,
  },
  {
    id: 'ptn-005',
    category: 'trademark_consultant',
    companyName: 'MarkShield IP',
    contactPerson: 'Deepa N.',
    city: 'Hyderabad',
    state: 'Telangana',
    serviceArea: 'PAN India',
    skills: ['Trademark search', 'Filing', 'Objection reply'],
    rating: 4.6,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 8,
    performanceScore: 85,
    commissionType: 'fixed',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Trademark and brand protection filings.',
    slaHours: 24,
  },
  {
    id: 'ptn-006',
    category: 'digital_marketing',
    companyName: 'Pulse Growth Studio',
    contactPerson: 'Arjun M.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    serviceArea: 'South India · remote',
    skills: ['Meta Ads', 'Google Ads', 'Funnel'],
    rating: 4.3,
    verificationStatus: 'verified',
    availability: 'limited',
    experienceYears: 6,
    performanceScore: 79,
    commissionType: 'percent',
    documentsStatus: 'partial',
    bankVerificationStatus: 'pending',
    summary: 'Performance marketing for local and D2C brands.',
    slaHours: 12,
  },
  {
    id: 'ptn-007',
    category: 'seo',
    companyName: 'RankCraft SEO',
    contactPerson: 'Lakshmi V.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    serviceArea: 'PAN India remote',
    skills: ['Technical SEO', 'Content', 'Local SEO'],
    rating: 4.5,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 5,
    performanceScore: 84,
    commissionType: 'retainer',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Organic growth and local SEO partner.',
    slaHours: 24,
  },
  {
    id: 'ptn-008',
    category: 'graphic_design',
    companyName: 'Karthik Design Studio',
    contactPerson: 'Karthik R.',
    city: 'Coimbatore',
    state: 'Tamil Nadu',
    serviceArea: 'Tamil Nadu · remote',
    skills: ['Brand', 'UI kits', 'Print'],
    rating: 4.6,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 8,
    performanceScore: 87,
    commissionType: 'fixed',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Linked creative partner (also used as ven-001 in Vendor Workspace).',
    slaHours: 36,
  },
  {
    id: 'ptn-009',
    category: 'website_development',
    companyName: 'PixelForge Labs',
    contactPerson: 'Naveen T.',
    city: 'Bengaluru',
    state: 'Karnataka',
    serviceArea: 'PAN India',
    skills: ['Next.js', 'CMS', 'E-commerce'],
    rating: 4.7,
    verificationStatus: 'verified',
    availability: 'limited',
    experienceYears: 11,
    performanceScore: 90,
    commissionType: 'hybrid',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Delivery partner for website and web apps.',
    slaHours: 24,
  },
  {
    id: 'ptn-010',
    category: 'ai_automation',
    companyName: 'AutomateX AI',
    contactPerson: 'Ritu S.',
    city: 'Pune',
    state: 'Maharashtra',
    serviceArea: 'PAN India remote',
    skills: ['Chatbots', 'Workflow automation', 'RAG'],
    rating: 4.2,
    verificationStatus: 'pending',
    availability: 'available',
    experienceYears: 4,
    performanceScore: 74,
    commissionType: 'percent',
    documentsStatus: 'submitted',
    bankVerificationStatus: 'pending',
    summary: 'AI automation and internal ops copilots.',
    slaHours: 48,
  },
  {
    id: 'ptn-011',
    category: 'hosting',
    companyName: 'CloudNest Hosting',
    contactPerson: 'Imran Q.',
    city: 'Hyderabad',
    state: 'Telangana',
    serviceArea: 'PAN India',
    skills: ['VPS', 'Managed WP', 'SSL', 'Backups'],
    rating: 4.1,
    verificationStatus: 'verified',
    availability: 'available',
    experienceYears: 9,
    performanceScore: 80,
    commissionType: 'percent',
    documentsStatus: 'verified',
    bankVerificationStatus: 'verified',
    summary: 'Hosting and uptime operations partner.',
    slaHours: 8,
  },
  {
    id: 'ptn-012',
    category: 'business_consultant',
    companyName: 'Northstar Business Advisors',
    contactPerson: 'Priya D.',
    city: 'Chennai',
    state: 'Tamil Nadu',
    serviceArea: 'South India',
    skills: ['SOP', 'Go-to-market', 'Unit economics'],
    rating: 4.4,
    verificationStatus: 'suspended',
    availability: 'unavailable',
    experienceYears: 15,
    performanceScore: 68,
    commissionType: 'retainer',
    documentsStatus: 'partial',
    bankVerificationStatus: 'failed',
    summary: 'Temporarily suspended pending document refresh.',
    slaHours: 72,
  },
];

export const demoPartnerPerformance: PartnerPerformance[] = demoPartners.map(
  (partner, index) => ({
    partnerId: partner.id,
    completedProjects: 8 + (index % 7) * 3,
    delayedProjects: index % 4,
    averageRating: partner.rating,
    customerSatisfaction: Math.min(98, Math.round(partner.rating * 20)),
    onTimeDeliveryPercent: Math.max(70, partner.performanceScore - 5),
    revisionCount: 1 + (index % 5),
    responseTimeHours: partner.slaHours / 2,
  }),
);

export const demoPartnerAssignments: PartnerAssignment[] = [
  {
    id: 'pa-1',
    partnerId: 'ptn-008',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    roleLabel: 'UI / Brand design',
    status: 'active',
    assignedAt: '2026-07-10',
    dueDate: '2026-07-28',
  },
  {
    id: 'pa-2',
    partnerId: 'ptn-008',
    projectId: 'prj-088',
    projectTitle: 'Coastal Dental — Brand Refresh',
    customerBusinessName: 'Coastal Dental',
    roleLabel: 'Logo pack',
    status: 'active',
    assignedAt: '2026-07-05',
    dueDate: '2026-07-24',
  },
  {
    id: 'pa-3',
    partnerId: 'ptn-002',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    customerBusinessName: 'GreenLeaf Organics',
    roleLabel: 'GST filing support',
    status: 'active',
    assignedAt: '2026-06-15',
    dueDate: '2026-07-31',
  },
  {
    id: 'pa-4',
    partnerId: 'ptn-009',
    projectId: 'prj-204',
    projectTitle: 'Sunrise Retail — Website Redesign',
    customerBusinessName: 'Sunrise Retail Pvt Ltd',
    roleLabel: 'CMS implementation assist',
    status: 'on_hold',
    assignedAt: '2026-07-18',
    dueDate: null,
  },
  {
    id: 'pa-5',
    partnerId: 'ptn-001',
    projectId: 'prj-311',
    projectTitle: 'GreenLeaf — GST Registration',
    customerBusinessName: 'GreenLeaf Organics',
    roleLabel: 'Entity docs review',
    status: 'completed',
    assignedAt: '2026-06-01',
    dueDate: '2026-06-20',
  },
];

export const demoPartnerPayments: PartnerPaymentSummary[] = [
  {
    partnerId: 'ptn-008',
    earnedInr: 85000,
    pendingInr: 45000,
    paidInr: 40000,
    lastPayoutAt: '2026-06-15',
    notes: 'Settlements mirrored from finance set-101 / set-103 (demo).',
  },
  {
    partnerId: 'ptn-002',
    earnedInr: 18000,
    pendingInr: 9000,
    paidInr: 9000,
    lastPayoutAt: '2026-06-25',
    notes: 'GST package split with U&V delivery.',
  },
  {
    partnerId: 'ptn-009',
    earnedInr: 120000,
    pendingInr: 0,
    paidInr: 120000,
    lastPayoutAt: '2026-05-30',
    notes: 'Prior completed engagement.',
  },
];

export const demoPartnerDocuments: PartnerDocument[] = [
  {
    id: 'pd-1',
    partnerId: 'ptn-008',
    name: 'Partner NDA',
    kind: 'nda',
    status: 'verified',
    uploadedAt: '2026-01-10',
  },
  {
    id: 'pd-2',
    partnerId: 'ptn-008',
    name: 'GST certificate',
    kind: 'gst',
    status: 'verified',
    uploadedAt: '2026-01-12',
  },
  {
    id: 'pd-3',
    partnerId: 'ptn-008',
    name: 'Bank verification',
    kind: 'bank',
    status: 'verified',
    uploadedAt: '2026-01-15',
  },
  {
    id: 'pd-4',
    partnerId: 'ptn-004',
    name: 'Partner agreement',
    kind: 'agreement',
    status: 'submitted',
    uploadedAt: '2026-07-01',
  },
  {
    id: 'pd-5',
    partnerId: 'ptn-012',
    name: 'KYC pack',
    kind: 'kyc',
    status: 'partial',
    uploadedAt: '2026-03-01',
  },
];

export const demoPartnerCommunications: PartnerCommunication[] = [
  {
    id: 'pc-1',
    partnerId: 'ptn-008',
    occurredAt: '2026-07-22T11:00:00+05:30',
    channel: 'whatsapp',
    title: 'UI kit mid-review',
    detail: 'Requested mobile breakpoint screens for homepage.',
    actorName: 'Arun Kumar',
  },
  {
    id: 'pc-2',
    partnerId: 'ptn-008',
    occurredAt: '2026-07-18T16:30:00+05:30',
    channel: 'email',
    title: 'Brand pack delivery',
    detail: 'Partner shared logo directions for Coastal Dental.',
    actorName: 'Karthik R.',
  },
  {
    id: 'pc-3',
    partnerId: 'ptn-002',
    occurredAt: '2026-07-20T10:00:00+05:30',
    channel: 'call',
    title: 'KYC clarification',
    detail: 'Discussed address proof mismatch for GST filing.',
    actorName: 'Meena R.',
  },
  {
    id: 'pc-4',
    partnerId: 'ptn-001',
    occurredAt: '2026-06-18T14:00:00+05:30',
    channel: 'meeting',
    title: 'Entity docs handover',
    detail: 'Completed entity document review for GreenLeaf.',
    actorName: 'Anitha S.',
  },
];

export const demoMarketplaceServices: MarketplaceService[] = [
  {
    id: 'svc-mkt-01',
    category: 'Compliance',
    subCategory: 'Company formation',
    title: 'Private Limited Company Registration',
    description: 'End-to-end incorporation with DSC, DIN, and MCA filing support.',
    estimatedPriceInr: 14999,
    estimatedDurationDays: 14,
    requiredDocuments: ['PAN', 'Aadhaar', 'Address proof', 'Photo'],
    suggestedPartnerIds: ['ptn-001', 'ptn-003'],
    customerEligibility: 'Founders with Indian residency documents',
    businessChecklist: [
      'Decide company name options',
      'Confirm shareholding',
      'Prepare registered office proof',
    ],
  },
  {
    id: 'svc-mkt-02',
    category: 'Compliance',
    subCategory: 'GST',
    title: 'GST Registration',
    description: 'GSTIN application, ARN tracking, and certificate delivery.',
    estimatedPriceInr: 4999,
    estimatedDurationDays: 10,
    requiredDocuments: ['PAN', 'Aadhaar', 'Business address proof', 'Bank proof'],
    suggestedPartnerIds: ['ptn-002', 'ptn-001'],
    customerEligibility: 'Businesses needing GSTIN for trading/services',
    businessChecklist: [
      'Confirm business constitution',
      'Collect landlord NOC if rented',
      'Validate bank account details',
    ],
  },
  {
    id: 'svc-mkt-03',
    category: 'Brand',
    subCategory: 'Trademark',
    title: 'Trademark Filing',
    description: 'Search, class selection, and trademark application filing.',
    estimatedPriceInr: 8999,
    estimatedDurationDays: 21,
    requiredDocuments: ['Brand name/logo', 'Applicant ID', 'User affidavit if needed'],
    suggestedPartnerIds: ['ptn-005', 'ptn-004'],
    customerEligibility: 'Businesses with distinctive brand assets',
    businessChecklist: [
      'Finalize brand mark',
      'Choose trademark classes',
      'Confirm applicant entity',
    ],
  },
  {
    id: 'svc-mkt-04',
    category: 'Digital',
    subCategory: 'Website',
    title: 'Business Website Development',
    description: 'Marketing website with CMS and lead capture.',
    estimatedPriceInr: 75000,
    estimatedDurationDays: 45,
    requiredDocuments: ['Brand kit', 'Content brief', 'Domain access'],
    suggestedPartnerIds: ['ptn-009', 'ptn-008', 'ptn-011'],
    customerEligibility: 'SMEs ready with brand basics',
    businessChecklist: [
      'Approve sitemap',
      'Provide content owners',
      'Confirm hosting preference',
    ],
  },
  {
    id: 'svc-mkt-05',
    category: 'Digital',
    subCategory: 'Marketing',
    title: 'Digital Marketing Starter Pack',
    description: 'Ads setup, tracking, and 30-day campaign management.',
    estimatedPriceInr: 35000,
    estimatedDurationDays: 30,
    requiredDocuments: ['Business page access', 'Offer creatives', 'Budget approval'],
    suggestedPartnerIds: ['ptn-006', 'ptn-007'],
    customerEligibility: 'Businesses with monthly ad budget ≥ ₹25k',
    businessChecklist: [
      'Define offers',
      'Set KPI targets',
      'Approve creative direction',
    ],
  },
  {
    id: 'svc-mkt-06',
    category: 'Technology',
    subCategory: 'Automation',
    title: 'AI Automation Pilot',
    description: 'Pilot chatbot or workflow automation for one ops process.',
    estimatedPriceInr: 55000,
    estimatedDurationDays: 28,
    requiredDocuments: ['Process notes', 'Sample data (masked)', 'Tool access'],
    suggestedPartnerIds: ['ptn-010', 'ptn-009'],
    customerEligibility: 'Teams with a clear repetitive workflow',
    businessChecklist: [
      'Pick one process to automate',
      'Mask sensitive data',
      'Assign internal owner',
    ],
  },
  {
    id: 'svc-mkt-07',
    category: 'Operations',
    subCategory: 'Hosting',
    title: 'Managed Hosting & Monitoring',
    description: 'Managed VPS/hosting with SSL, backups, and uptime checks.',
    estimatedPriceInr: 12000,
    estimatedDurationDays: 7,
    requiredDocuments: ['Domain registrar access', 'Current hosting details'],
    suggestedPartnerIds: ['ptn-011'],
    customerEligibility: 'Sites needing reliable uptime',
    businessChecklist: [
      'Confirm traffic expectations',
      'List critical apps',
      'Set backup retention',
    ],
  },
  {
    id: 'svc-mkt-08',
    category: 'Brand',
    subCategory: 'Design',
    title: 'Brand Identity Pack',
    description: 'Logo directions, usage sheet, and basic brand guidelines.',
    estimatedPriceInr: 45000,
    estimatedDurationDays: 21,
    requiredDocuments: ['Business brief', 'Competitor references'],
    suggestedPartnerIds: ['ptn-008', 'ptn-005'],
    customerEligibility: 'New or rebranding businesses',
    businessChecklist: [
      'Share brand personality',
      'Approve moodboard',
      'Select final direction',
    ],
  },
];

export const demoBusinessTemplates: BusinessServiceTemplate[] = [
  {
    id: 'restaurant',
    name: 'Restaurant',
    summary: 'Launch-ready compliance, brand, and digital presence for F&B.',
    requiredRegistrations: ['FSSAI', 'GST', 'Shop & Establishment'],
    requiredLicenses: ['Fire NOC (as applicable)', 'Local trade license'],
    recommendedServiceIds: ['svc-mkt-02', 'svc-mkt-08', 'svc-mkt-04', 'svc-mkt-05'],
    suggestedTimelineWeeks: 10,
    suggestedBudgetInr: { min: 120000, max: 350000 },
    requiredPartnerCategories: [
      'gst_consultant',
      'graphic_design',
      'website_development',
      'digital_marketing',
    ],
  },
  {
    id: 'travel_agency',
    name: 'Travel Agency',
    summary: 'Agency setup with brand, website, and booking-ready operations.',
    requiredRegistrations: ['GST', 'Partnership/Company'],
    requiredLicenses: ['IATA (optional)', 'State tourism registration (optional)'],
    recommendedServiceIds: ['svc-mkt-01', 'svc-mkt-04', 'svc-mkt-05', 'svc-mkt-07'],
    suggestedTimelineWeeks: 8,
    suggestedBudgetInr: { min: 150000, max: 400000 },
    requiredPartnerCategories: [
      'company_registration',
      'website_development',
      'digital_marketing',
      'hosting',
    ],
  },
  {
    id: 'school',
    name: 'School',
    summary: 'Institutional digital presence and compliance advisory pack.',
    requiredRegistrations: ['Trust/Society/Company', 'GST if applicable'],
    requiredLicenses: ['Education board affiliation (context)', 'Fire safety'],
    recommendedServiceIds: ['svc-mkt-04', 'svc-mkt-08', 'svc-mkt-07'],
    suggestedTimelineWeeks: 12,
    suggestedBudgetInr: { min: 200000, max: 600000 },
    requiredPartnerCategories: [
      'lawyer',
      'website_development',
      'graphic_design',
      'hosting',
    ],
  },
  {
    id: 'hospital',
    name: 'Hospital',
    summary: 'Healthcare brand, web presence, and compliance partner map.',
    requiredRegistrations: ['Clinical establishment', 'GST'],
    requiredLicenses: ['Biomedical waste', 'Fire NOC', 'Pharmacy license (if any)'],
    recommendedServiceIds: ['svc-mkt-04', 'svc-mkt-08', 'svc-mkt-03'],
    suggestedTimelineWeeks: 14,
    suggestedBudgetInr: { min: 250000, max: 800000 },
    requiredPartnerCategories: [
      'lawyer',
      'website_development',
      'graphic_design',
      'trademark_consultant',
    ],
  },
  {
    id: 'retail_shop',
    name: 'Retail Shop',
    summary: 'Store launch pack: GST, brand, website, and local SEO.',
    requiredRegistrations: ['GST', 'Shop & Establishment'],
    requiredLicenses: ['Trade license'],
    recommendedServiceIds: ['svc-mkt-02', 'svc-mkt-08', 'svc-mkt-04', 'svc-mkt-05'],
    suggestedTimelineWeeks: 6,
    suggestedBudgetInr: { min: 80000, max: 250000 },
    requiredPartnerCategories: [
      'gst_consultant',
      'graphic_design',
      'seo',
      'website_development',
    ],
  },
  {
    id: 'manufacturing',
    name: 'Manufacturing',
    summary: 'Entity, GST, brand, and B2B website foundation.',
    requiredRegistrations: ['Company/LLP', 'GST', 'Udyam'],
    requiredLicenses: ['Factory license (as applicable)', 'Pollution NOC'],
    recommendedServiceIds: ['svc-mkt-01', 'svc-mkt-02', 'svc-mkt-04', 'svc-mkt-03'],
    suggestedTimelineWeeks: 12,
    suggestedBudgetInr: { min: 200000, max: 700000 },
    requiredPartnerCategories: [
      'company_registration',
      'gst_consultant',
      'chartered_accountant',
      'website_development',
    ],
  },
  {
    id: 'construction',
    name: 'Construction',
    summary: 'Contractor readiness with compliance and lead website.',
    requiredRegistrations: ['GST', 'Company/Proprietorship'],
    requiredLicenses: ['Contractor license', 'Labour compliance'],
    recommendedServiceIds: ['svc-mkt-02', 'svc-mkt-04', 'svc-mkt-05'],
    suggestedTimelineWeeks: 8,
    suggestedBudgetInr: { min: 100000, max: 300000 },
    requiredPartnerCategories: [
      'gst_consultant',
      'lawyer',
      'website_development',
      'digital_marketing',
    ],
  },
  {
    id: 'it_company',
    name: 'IT Company',
    summary: 'Tech company launch: incorporation, brand, site, hosting, AI ops.',
    requiredRegistrations: ['Private Limited', 'GST', 'DPIIT (optional)'],
    requiredLicenses: ['IEC (if export)'],
    recommendedServiceIds: [
      'svc-mkt-01',
      'svc-mkt-04',
      'svc-mkt-07',
      'svc-mkt-06',
    ],
    suggestedTimelineWeeks: 10,
    suggestedBudgetInr: { min: 180000, max: 550000 },
    requiredPartnerCategories: [
      'company_registration',
      'website_development',
      'hosting',
      'ai_automation',
    ],
  },
  {
    id: 'mlm_company',
    name: 'MLM Company',
    summary: 'Network marketing readiness with legal caution and digital stack.',
    requiredRegistrations: ['Company', 'GST'],
    requiredLicenses: ['Legal opinion on compensation plan'],
    recommendedServiceIds: ['svc-mkt-01', 'svc-mkt-04', 'svc-mkt-03', 'svc-mkt-05'],
    suggestedTimelineWeeks: 12,
    suggestedBudgetInr: { min: 300000, max: 1200000 },
    requiredPartnerCategories: [
      'company_registration',
      'lawyer',
      'website_development',
      'digital_marketing',
    ],
  },
  {
    id: 'startup',
    name: 'Startup',
    summary: 'Founder pack: entity, IP, brand, MVP web, and growth pilot.',
    requiredRegistrations: ['Private Limited / LLP', 'GST'],
    requiredLicenses: ['DPIIT recognition (optional)'],
    recommendedServiceIds: [
      'svc-mkt-01',
      'svc-mkt-03',
      'svc-mkt-08',
      'svc-mkt-04',
      'svc-mkt-06',
    ],
    suggestedTimelineWeeks: 10,
    suggestedBudgetInr: { min: 150000, max: 500000 },
    requiredPartnerCategories: [
      'company_registration',
      'trademark_consultant',
      'graphic_design',
      'website_development',
      'ai_automation',
    ],
  },
];
