import type {
  AttendanceRow,
  AdminUser,
  CalendarEvent,
  Category,
  Customer,
  Deal,
  EmailEvent,
  Employee,
  FollowUp,
  Invoice,
  Lead,
  LeaveRequest,
  LedgerEntry,
  NoteItem,
  Payment,
  PayrollRow,
  PermissionItem,
  Product,
  PurchaseOrder,
  Quotation,
  RoleItem,
  SalesOrder,
  Supplier,
  TaskItem,
} from './types';

export function formatInr(amount: number) {
  return new Intl.NumberFormat('en-IN', {
    style: 'currency',
    currency: 'INR',
    maximumFractionDigits: 0,
  }).format(amount);
}

export const demoCustomers: Customer[] = [
  {
    id: 'CUS-1001',
    name: 'Ravi Krishnan',
    company: 'Southern Retail Pvt Ltd',
    email: 'ravi@southern.demo',
    phone: '+91 ••••• •••21',
    city: 'Chennai',
    status: 'active',
    owner: 'Karthik Rao',
    lifetimeValue: 1840000,
    openDeals: 2,
    lastContact: '2026-07-18',
  },
  {
    id: 'CUS-1002',
    name: 'Meera Iyer',
    company: 'BluePeak Traders',
    email: 'meera@bluepeak.demo',
    phone: '+91 ••••• •••44',
    city: 'Coimbatore',
    status: 'active',
    owner: 'Karthik Rao',
    lifetimeValue: 920000,
    openDeals: 1,
    lastContact: '2026-07-16',
  },
  {
    id: 'CUS-1003',
    name: 'Imran Ali',
    company: 'Orbit Logistics',
    email: 'imran@orbit.demo',
    phone: '+91 ••••• •••88',
    city: 'Bengaluru',
    status: 'prospect',
    owner: 'Priya Menon',
    lifetimeValue: 0,
    openDeals: 1,
    lastContact: '2026-07-12',
  },
  {
    id: 'CUS-1004',
    name: 'Sneha Patel',
    company: 'Cascade Foods',
    email: 'sneha@cascade.demo',
    phone: '+91 ••••• •••09',
    city: 'Madurai',
    status: 'active',
    owner: 'Karthik Rao',
    lifetimeValue: 640000,
    openDeals: 0,
    lastContact: '2026-07-08',
  },
  {
    id: 'CUS-1005',
    name: 'John Mathew',
    company: 'Harbor Components',
    email: 'john@harbor.demo',
    phone: '+91 ••••• •••67',
    city: 'Kochi',
    status: 'inactive',
    owner: 'Priya Menon',
    lifetimeValue: 210000,
    openDeals: 0,
    lastContact: '2026-05-22',
  },
  {
    id: 'CUS-1006',
    name: 'Lakshmi Devi',
    company: 'Nimbus Wellness',
    email: 'lakshmi@nimbus.demo',
    phone: '+91 ••••• •••33',
    city: 'Hyderabad',
    status: 'active',
    owner: 'Karthik Rao',
    lifetimeValue: 1180000,
    openDeals: 3,
    lastContact: '2026-07-20',
  },
];

export const demoLeads: Lead[] = [
  {
    id: 'LEAD-201',
    name: 'Arjun Nair',
    company: 'Vista Mart',
    source: 'Website',
    score: 82,
    status: 'qualified',
    owner: 'Karthik Rao',
    createdAt: '2026-07-14',
  },
  {
    id: 'LEAD-202',
    name: 'Fatima Begum',
    company: 'Pearl Clinics',
    source: 'Referral',
    score: 74,
    status: 'contacted',
    owner: 'Karthik Rao',
    createdAt: '2026-07-15',
  },
  {
    id: 'LEAD-203',
    name: 'Dev Patel',
    company: 'Axis Packers',
    source: 'Expo',
    score: 61,
    status: 'new',
    owner: 'Priya Menon',
    createdAt: '2026-07-18',
  },
  {
    id: 'LEAD-204',
    name: 'Hannah George',
    company: 'Leaf & Co',
    source: 'LinkedIn',
    score: 48,
    status: 'lost',
    owner: 'Karthik Rao',
    createdAt: '2026-07-02',
  },
  {
    id: 'LEAD-205',
    name: 'Suresh Balan',
    company: 'Metro Hardware',
    source: 'Cold call',
    score: 69,
    status: 'contacted',
    owner: 'Karthik Rao',
    createdAt: '2026-07-19',
  },
];

export const demoFollowUps: FollowUp[] = [
  {
    id: 'FU-11',
    relatedTo: 'CUS-1001 · Southern Retail',
    type: 'call',
    dueDate: '2026-07-22',
    status: 'open',
    owner: 'Karthik Rao',
    note: 'Confirm Q3 replenishment volumes',
  },
  {
    id: 'FU-12',
    relatedTo: 'LEAD-201 · Vista Mart',
    type: 'meeting',
    dueDate: '2026-07-23',
    status: 'open',
    owner: 'Karthik Rao',
    note: 'Product walkthrough for store ops',
  },
  {
    id: 'FU-13',
    relatedTo: 'CUS-1006 · Nimbus Wellness',
    type: 'email',
    dueDate: '2026-07-21',
    status: 'overdue',
    owner: 'Karthik Rao',
    note: 'Send revised quotation QT-441',
  },
  {
    id: 'FU-14',
    relatedTo: 'LEAD-202 · Pearl Clinics',
    type: 'meeting',
    dueDate: '2026-07-25',
    status: 'open',
    owner: 'Priya Menon',
    note: 'Stakeholder discovery',
  },
  {
    id: 'FU-15',
    relatedTo: 'CUS-1002 · BluePeak',
    type: 'whatsapp',
    dueDate: '2026-07-18',
    status: 'done',
    owner: 'Karthik Rao',
    note: 'Shared delivery ETA',
  },
];

export const demoQuotations: Quotation[] = [
  {
    id: 'QT-441',
    customer: 'Nimbus Wellness',
    amount: 286000,
    status: 'sent',
    validUntil: '2026-07-30',
    owner: 'Karthik Rao',
  },
  {
    id: 'QT-438',
    customer: 'Southern Retail',
    amount: 512000,
    status: 'accepted',
    validUntil: '2026-07-20',
    owner: 'Karthik Rao',
  },
  {
    id: 'QT-430',
    customer: 'BluePeak Traders',
    amount: 148000,
    status: 'draft',
    validUntil: '2026-08-01',
    owner: 'Karthik Rao',
  },
  {
    id: 'QT-421',
    customer: 'Orbit Logistics',
    amount: 96000,
    status: 'rejected',
    validUntil: '2026-07-10',
    owner: 'Priya Menon',
  },
  {
    id: 'QT-410',
    customer: 'Cascade Foods',
    amount: 210000,
    status: 'expired',
    validUntil: '2026-06-30',
    owner: 'Karthik Rao',
  },
];

export const demoSalesOrders: SalesOrder[] = [
  {
    id: 'SO-7781',
    customer: 'Southern Retail',
    amount: 512000,
    status: 'processing',
    orderDate: '2026-07-18',
    items: 18,
  },
  {
    id: 'SO-7760',
    customer: 'Nimbus Wellness',
    amount: 164000,
    status: 'confirmed',
    orderDate: '2026-07-16',
    items: 9,
  },
  {
    id: 'SO-7722',
    customer: 'BluePeak Traders',
    amount: 88000,
    status: 'shipped',
    orderDate: '2026-07-10',
    items: 6,
  },
  {
    id: 'SO-7701',
    customer: 'Cascade Foods',
    amount: 121000,
    status: 'delivered',
    orderDate: '2026-07-02',
    items: 11,
  },
  {
    id: 'SO-7688',
    customer: 'Harbor Components',
    amount: 42000,
    status: 'cancelled',
    orderDate: '2026-06-28',
    items: 3,
  },
];

export const demoDeals: Deal[] = [
  {
    id: 'DEAL-91',
    name: 'Southern Q3 Expansion',
    customer: 'Southern Retail',
    stage: 'negotiation',
    value: 780000,
    probability: 70,
    owner: 'Karthik Rao',
    closeDate: '2026-08-15',
  },
  {
    id: 'DEAL-88',
    name: 'Nimbus ERP Pilot',
    customer: 'Nimbus Wellness',
    stage: 'proposal',
    value: 450000,
    probability: 55,
    owner: 'Karthik Rao',
    closeDate: '2026-08-05',
  },
  {
    id: 'DEAL-84',
    name: 'Orbit WMS Rollout',
    customer: 'Orbit Logistics',
    stage: 'qualification',
    value: 320000,
    probability: 35,
    owner: 'Priya Menon',
    closeDate: '2026-09-01',
  },
  {
    id: 'DEAL-80',
    name: 'BluePeak Annual',
    customer: 'BluePeak Traders',
    stage: 'won',
    value: 210000,
    probability: 100,
    owner: 'Karthik Rao',
    closeDate: '2026-07-12',
  },
  {
    id: 'DEAL-77',
    name: 'Harbor Spare Parts',
    customer: 'Harbor Components',
    stage: 'lost',
    value: 95000,
    probability: 0,
    owner: 'Priya Menon',
    closeDate: '2026-07-01',
  },
];

export const demoTasks: TaskItem[] = [
  {
    id: 'TSK-1',
    title: 'Prepare proposal deck',
    relatedTo: 'DEAL-88',
    priority: 'high',
    status: 'in_progress',
    dueDate: '2026-07-22',
    owner: 'Karthik Rao',
  },
  {
    id: 'TSK-2',
    title: 'Update customer contacts',
    relatedTo: 'CUS-1002',
    priority: 'medium',
    status: 'todo',
    dueDate: '2026-07-23',
    owner: 'Karthik Rao',
  },
  {
    id: 'TSK-3',
    title: 'Approve leave backlog',
    relatedTo: 'HR',
    priority: 'high',
    status: 'todo',
    dueDate: '2026-07-22',
    owner: 'Anitha Selvan',
  },
  {
    id: 'TSK-4',
    title: 'Reconcile June invoices',
    relatedTo: 'Accounting',
    priority: 'medium',
    status: 'done',
    dueDate: '2026-07-15',
    owner: 'Priya Menon',
  },
  {
    id: 'TSK-5',
    title: 'Schedule product demo',
    relatedTo: 'LEAD-201',
    priority: 'low',
    status: 'todo',
    dueDate: '2026-07-24',
    owner: 'Karthik Rao',
  },
];

export const demoCalendar: CalendarEvent[] = [
  {
    id: 'CAL-1',
    title: 'Demo · Vista Mart',
    date: '2026-07-23',
    time: '11:00',
    type: 'demo',
    attendees: 'Karthik, Arjun',
  },
  {
    id: 'CAL-2',
    title: 'Negotiation · Southern',
    date: '2026-07-22',
    time: '16:30',
    type: 'meeting',
    attendees: 'Karthik, Ravi',
  },
  {
    id: 'CAL-3',
    title: 'HR weekly sync',
    date: '2026-07-24',
    time: '10:00',
    type: 'internal',
    attendees: 'Anitha, Priya',
  },
  {
    id: 'CAL-4',
    title: 'Discovery · Pearl Clinics',
    date: '2026-07-25',
    time: '14:00',
    type: 'call',
    attendees: 'Priya, Fatima',
  },
  {
    id: 'CAL-5',
    title: 'Ops standup',
    date: '2026-07-22',
    time: '09:30',
    type: 'internal',
    attendees: 'Admin team',
  },
];

export const demoNotes: NoteItem[] = [
  {
    id: 'NOTE-1',
    title: 'Budget timing',
    body: 'Customer wants phased billing across Aug–Oct.',
    relatedTo: 'DEAL-91',
    author: 'Karthik Rao',
    updatedAt: '2026-07-18',
  },
  {
    id: 'NOTE-2',
    title: 'Competitor mention',
    body: 'Evaluating two local ERP vendors; emphasize inventory accuracy.',
    relatedTo: 'LEAD-201',
    author: 'Karthik Rao',
    updatedAt: '2026-07-16',
  },
  {
    id: 'NOTE-3',
    title: 'Onboarding risk',
    body: 'Warehouse staff need weekend training slots.',
    relatedTo: 'CUS-1006',
    author: 'Priya Menon',
    updatedAt: '2026-07-14',
  },
  {
    id: 'NOTE-4',
    title: 'Payroll cutoff',
    body: 'July payroll lock on 28th evening.',
    relatedTo: 'HR',
    author: 'Anitha Selvan',
    updatedAt: '2026-07-20',
  },
];

export const demoEmails: EmailEvent[] = [
  {
    id: 'EM-1',
    subject: 'Revised quotation QT-441',
    from: 'sales@uandv.com',
    to: 'lakshmi@nimbus.demo',
    date: '2026-07-20 09:42',
    direction: 'outbound',
    preview: 'Sharing the updated commercial proposal with volume pricing…',
  },
  {
    id: 'EM-2',
    subject: 'Re: Delivery windows',
    from: 'ravi@southern.demo',
    to: 'sales@uandv.com',
    date: '2026-07-18 17:10',
    direction: 'inbound',
    preview: 'Can we split SO-7781 across two warehouse drops?',
  },
  {
    id: 'EM-3',
    subject: 'Demo confirmation',
    from: 'sales@uandv.com',
    to: 'arjun@vista.demo',
    date: '2026-07-17 11:05',
    direction: 'outbound',
    preview: 'Confirming Thursday 11:00 IST for the product walkthrough…',
  },
  {
    id: 'EM-4',
    subject: 'Invoice INV-552 reminder',
    from: 'admin@uandv.com',
    to: 'meera@bluepeak.demo',
    date: '2026-07-15 08:30',
    direction: 'outbound',
    preview: 'Friendly reminder that invoice INV-552 is due this week…',
  },
];

export const demoEmployees: Employee[] = [
  {
    id: 'EMP-01',
    name: 'Priya Menon',
    email: 'admin@uandv.com',
    department: 'Operations',
    role: 'Platform Admin',
    status: 'active',
    joinDate: '2024-02-01',
    salary: 120000,
  },
  {
    id: 'EMP-02',
    name: 'Karthik Rao',
    email: 'sales@uandv.com',
    department: 'Sales',
    role: 'Sales Executive',
    status: 'active',
    joinDate: '2024-06-12',
    salary: 75000,
  },
  {
    id: 'EMP-03',
    name: 'Anitha Selvan',
    email: 'hr@uandv.com',
    department: 'HR',
    role: 'HR Manager',
    status: 'active',
    joinDate: '2024-03-18',
    salary: 85000,
  },
  {
    id: 'EMP-04',
    name: 'Vignesh Kumar',
    email: 'vignesh@uandv.demo',
    department: 'Warehouse',
    role: 'Store Lead',
    status: 'active',
    joinDate: '2025-01-09',
    salary: 48000,
  },
  {
    id: 'EMP-05',
    name: 'Divya R',
    email: 'divya@uandv.demo',
    department: 'Finance',
    role: 'Accountant',
    status: 'on_leave',
    joinDate: '2025-04-02',
    salary: 56000,
  },
  {
    id: 'EMP-06',
    name: 'Mohammed Irfan',
    email: 'irfan@uandv.demo',
    department: 'Sales',
    role: 'BDR',
    status: 'active',
    joinDate: '2025-11-20',
    salary: 42000,
  },
];

export const demoAttendance: AttendanceRow[] = [
  {
    id: 'ATT-1',
    employee: 'Karthik Rao',
    date: '2026-07-21',
    checkIn: '09:12',
    checkOut: '18:05',
    status: 'present',
  },
  {
    id: 'ATT-2',
    employee: 'Anitha Selvan',
    date: '2026-07-21',
    checkIn: '09:01',
    checkOut: '17:55',
    status: 'present',
  },
  {
    id: 'ATT-3',
    employee: 'Vignesh Kumar',
    date: '2026-07-21',
    checkIn: '09:28',
    checkOut: '18:20',
    status: 'late',
  },
  {
    id: 'ATT-4',
    employee: 'Divya R',
    date: '2026-07-21',
    checkIn: '—',
    checkOut: '—',
    status: 'absent',
  },
  {
    id: 'ATT-5',
    employee: 'Mohammed Irfan',
    date: '2026-07-21',
    checkIn: '09:05',
    checkOut: '17:40',
    status: 'remote',
  },
];

export const demoLeave: LeaveRequest[] = [
  {
    id: 'LV-31',
    employee: 'Divya R',
    type: 'sick',
    from: '2026-07-20',
    to: '2026-07-22',
    days: 3,
    status: 'approved',
  },
  {
    id: 'LV-32',
    employee: 'Mohammed Irfan',
    type: 'casual',
    from: '2026-07-28',
    to: '2026-07-28',
    days: 1,
    status: 'pending',
  },
  {
    id: 'LV-33',
    employee: 'Vignesh Kumar',
    type: 'earned',
    from: '2026-08-04',
    to: '2026-08-08',
    days: 5,
    status: 'pending',
  },
  {
    id: 'LV-34',
    employee: 'Karthik Rao',
    type: 'casual',
    from: '2026-06-12',
    to: '2026-06-12',
    days: 1,
    status: 'approved',
  },
  {
    id: 'LV-35',
    employee: 'Anitha Selvan',
    type: 'unpaid',
    from: '2026-05-02',
    to: '2026-05-03',
    days: 2,
    status: 'rejected',
  },
];

export const demoPayroll: PayrollRow[] = [
  {
    id: 'PAY-JUL-01',
    employee: 'Priya Menon',
    period: 'Jul 2026',
    gross: 120000,
    deductions: 18000,
    net: 102000,
    status: 'processed',
  },
  {
    id: 'PAY-JUL-02',
    employee: 'Karthik Rao',
    period: 'Jul 2026',
    gross: 75000,
    deductions: 9800,
    net: 65200,
    status: 'processed',
  },
  {
    id: 'PAY-JUL-03',
    employee: 'Anitha Selvan',
    period: 'Jul 2026',
    gross: 85000,
    deductions: 11200,
    net: 73800,
    status: 'draft',
  },
  {
    id: 'PAY-JUL-04',
    employee: 'Vignesh Kumar',
    period: 'Jul 2026',
    gross: 48000,
    deductions: 5200,
    net: 42800,
    status: 'draft',
  },
  {
    id: 'PAY-JUN-02',
    employee: 'Karthik Rao',
    period: 'Jun 2026',
    gross: 75000,
    deductions: 9800,
    net: 65200,
    status: 'paid',
  },
];

export const demoProducts: Product[] = [
  {
    id: 'PRD-01',
    name: 'Industrial Pack Tape',
    sku: 'IPT-100',
    category: 'Packaging',
    price: 240,
    cost: 140,
    stock: 820,
    reorderLevel: 200,
  },
  {
    id: 'PRD-02',
    name: 'Barcode Scanner Pro',
    sku: 'BSP-220',
    category: 'Hardware',
    price: 8900,
    cost: 5400,
    stock: 46,
    reorderLevel: 15,
  },
  {
    id: 'PRD-03',
    name: 'Warehouse Tote Bin',
    sku: 'WTB-40',
    category: 'Storage',
    price: 680,
    cost: 390,
    stock: 210,
    reorderLevel: 80,
  },
  {
    id: 'PRD-04',
    name: 'Thermal Label Roll',
    sku: 'TLR-80',
    category: 'Packaging',
    price: 320,
    cost: 180,
    stock: 64,
    reorderLevel: 100,
  },
  {
    id: 'PRD-05',
    name: 'Handheld PDA',
    sku: 'HPD-5',
    category: 'Hardware',
    price: 24500,
    cost: 16800,
    stock: 18,
    reorderLevel: 8,
  },
  {
    id: 'PRD-06',
    name: 'Safety Gloves Box',
    sku: 'SGB-12',
    category: 'Safety',
    price: 560,
    cost: 300,
    stock: 340,
    reorderLevel: 120,
  },
];

export const demoCategories: Category[] = [
  {
    id: 'CAT-1',
    name: 'Packaging',
    products: 2,
    description: 'Consumables for packing and labeling',
  },
  {
    id: 'CAT-2',
    name: 'Hardware',
    products: 2,
    description: 'Scanners, PDAs, and devices',
  },
  {
    id: 'CAT-3',
    name: 'Storage',
    products: 1,
    description: 'Bins, racks, and storage aids',
  },
  {
    id: 'CAT-4',
    name: 'Safety',
    products: 1,
    description: 'PPE and warehouse safety items',
  },
];

export const demoPurchases: PurchaseOrder[] = [
  {
    id: 'PO-551',
    supplier: 'Alpha Supplies',
    amount: 186000,
    status: 'ordered',
    orderDate: '2026-07-12',
    expectedDate: '2026-07-24',
  },
  {
    id: 'PO-548',
    supplier: 'Delta Plastics',
    amount: 64000,
    status: 'received',
    orderDate: '2026-07-02',
    expectedDate: '2026-07-10',
  },
  {
    id: 'PO-540',
    supplier: 'Nova Devices',
    amount: 312000,
    status: 'draft',
    orderDate: '2026-07-19',
    expectedDate: '2026-08-02',
  },
  {
    id: 'PO-533',
    supplier: 'Alpha Supplies',
    amount: 42000,
    status: 'cancelled',
    orderDate: '2026-06-20',
    expectedDate: '2026-06-28',
  },
];

export const demoSuppliers: Supplier[] = [
  {
    id: 'SUP-1',
    name: 'Alpha Supplies',
    contact: 'Suresh',
    email: 'suresh@alpha.demo',
    city: 'Chennai',
    rating: 4.6,
    openPos: 1,
  },
  {
    id: 'SUP-2',
    name: 'Delta Plastics',
    contact: 'Nisha',
    email: 'nisha@delta.demo',
    city: 'Coimbatore',
    rating: 4.2,
    openPos: 0,
  },
  {
    id: 'SUP-3',
    name: 'Nova Devices',
    contact: 'Aravind',
    email: 'aravind@nova.demo',
    city: 'Bengaluru',
    rating: 4.8,
    openPos: 1,
  },
  {
    id: 'SUP-4',
    name: 'EastCoast Paper',
    contact: 'Helen',
    email: 'helen@eastcoast.demo',
    city: 'Tuticorin',
    rating: 3.9,
    openPos: 0,
  },
];

export const demoIncome: LedgerEntry[] = [
  {
    id: 'INC-1',
    date: '2026-07-18',
    category: 'Sales',
    description: 'SO-7781 advance',
    amount: 200000,
    method: 'NEFT',
  },
  {
    id: 'INC-2',
    date: '2026-07-16',
    category: 'Sales',
    description: 'SO-7760 payment',
    amount: 164000,
    method: 'UPI',
  },
  {
    id: 'INC-3',
    date: '2026-07-10',
    category: 'Service',
    description: 'Implementation fee',
    amount: 75000,
    method: 'NEFT',
  },
  {
    id: 'INC-4',
    date: '2026-07-02',
    category: 'Sales',
    description: 'SO-7701 settlement',
    amount: 121000,
    method: 'Cheque',
  },
];

export const demoExpense: LedgerEntry[] = [
  {
    id: 'EXP-1',
    date: '2026-07-19',
    category: 'Payroll',
    description: 'Partial payroll run',
    amount: 180000,
    method: 'NEFT',
  },
  {
    id: 'EXP-2',
    date: '2026-07-14',
    category: 'Purchase',
    description: 'PO-551 deposit',
    amount: 60000,
    method: 'NEFT',
  },
  {
    id: 'EXP-3',
    date: '2026-07-11',
    category: 'Ops',
    description: 'Warehouse utilities',
    amount: 28000,
    method: 'UPI',
  },
  {
    id: 'EXP-4',
    date: '2026-07-05',
    category: 'Marketing',
    description: 'Lead ads campaign',
    amount: 35000,
    method: 'Card',
  },
];

export const demoInvoices: Invoice[] = [
  {
    id: 'INV-552',
    customer: 'BluePeak Traders',
    amount: 88000,
    status: 'overdue',
    issueDate: '2026-06-28',
    dueDate: '2026-07-12',
  },
  {
    id: 'INV-560',
    customer: 'Southern Retail',
    amount: 256000,
    status: 'sent',
    issueDate: '2026-07-18',
    dueDate: '2026-08-01',
  },
  {
    id: 'INV-561',
    customer: 'Nimbus Wellness',
    amount: 164000,
    status: 'paid',
    issueDate: '2026-07-16',
    dueDate: '2026-07-30',
  },
  {
    id: 'INV-548',
    customer: 'Cascade Foods',
    amount: 121000,
    status: 'paid',
    issueDate: '2026-07-02',
    dueDate: '2026-07-16',
  },
  {
    id: 'INV-545',
    customer: 'Orbit Logistics',
    amount: 48000,
    status: 'draft',
    issueDate: '2026-07-20',
    dueDate: '2026-08-05',
  },
];

export const demoPayments: Payment[] = [
  {
    id: 'PMT-901',
    invoiceId: 'INV-561',
    customer: 'Nimbus Wellness',
    amount: 164000,
    method: 'UPI',
    date: '2026-07-16',
    status: 'completed',
  },
  {
    id: 'PMT-898',
    invoiceId: 'INV-548',
    customer: 'Cascade Foods',
    amount: 121000,
    method: 'NEFT',
    date: '2026-07-08',
    status: 'completed',
  },
  {
    id: 'PMT-890',
    invoiceId: 'INV-552',
    customer: 'BluePeak Traders',
    amount: 40000,
    method: 'UPI',
    date: '2026-07-19',
    status: 'pending',
  },
  {
    id: 'PMT-880',
    invoiceId: 'INV-540',
    customer: 'Harbor Components',
    amount: 22000,
    method: 'Card',
    date: '2026-06-30',
    status: 'failed',
  },
];

export const demoUsers: AdminUser[] = [
  {
    id: 'USR-ADMIN',
    name: 'Priya Menon',
    email: 'admin@uandv.com',
    role: 'Admin',
    status: 'active',
    lastLogin: '2026-07-22 09:10',
  },
  {
    id: 'USR-SALES',
    name: 'Karthik Rao',
    email: 'sales@uandv.com',
    role: 'Sales',
    status: 'active',
    lastLogin: '2026-07-22 08:45',
  },
  {
    id: 'USR-HR',
    name: 'Anitha Selvan',
    email: 'hr@uandv.com',
    role: 'HR',
    status: 'active',
    lastLogin: '2026-07-21 18:02',
  },
  {
    id: 'USR-FIN',
    name: 'Divya R',
    email: 'divya@uandv.demo',
    role: 'Finance',
    status: 'invited',
    lastLogin: '—',
  },
  {
    id: 'USR-WH',
    name: 'Vignesh Kumar',
    email: 'vignesh@uandv.demo',
    role: 'Warehouse',
    status: 'disabled',
    lastLogin: '2026-06-01 10:22',
  },
];

export const demoRoles: RoleItem[] = [
  {
    id: 'ROLE-1',
    name: 'Admin',
    users: 1,
    description: 'Full access across ERP, CRM, HR, and settings',
  },
  {
    id: 'ROLE-2',
    name: 'Sales',
    users: 2,
    description: 'Customers, pipeline, quotations, and sales reports',
  },
  {
    id: 'ROLE-3',
    name: 'HR',
    users: 1,
    description: 'Employees, attendance, leave, and payroll views',
  },
  {
    id: 'ROLE-4',
    name: 'Finance',
    users: 1,
    description: 'Invoices, payments, and accounting modules',
  },
  {
    id: 'ROLE-5',
    name: 'Warehouse',
    users: 1,
    description: 'Inventory, stock, and purchase receiving',
  },
];

export const demoPermissions: PermissionItem[] = [
  {
    id: 'PERM-1',
    module: 'Customers',
    action: 'read/write',
    admin: true,
    sales: true,
    hr: false,
  },
  {
    id: 'PERM-2',
    module: 'Pipeline',
    action: 'read/write',
    admin: true,
    sales: true,
    hr: false,
  },
  {
    id: 'PERM-3',
    module: 'HR',
    action: 'read/write',
    admin: true,
    sales: false,
    hr: true,
  },
  {
    id: 'PERM-4',
    module: 'Inventory',
    action: 'read/write',
    admin: true,
    sales: false,
    hr: false,
  },
  {
    id: 'PERM-5',
    module: 'Accounting',
    action: 'read/write',
    admin: true,
    sales: false,
    hr: false,
  },
  {
    id: 'PERM-6',
    module: 'Reports',
    action: 'read',
    admin: true,
    sales: true,
    hr: false,
  },
  {
    id: 'PERM-7',
    module: 'Admin',
    action: 'manage',
    admin: true,
    sales: false,
    hr: false,
  },
];

export const demoSalesChart = [
  { label: 'Feb', value: 420 },
  { label: 'Mar', value: 510 },
  { label: 'Apr', value: 480 },
  { label: 'May', value: 620 },
  { label: 'Jun', value: 710 },
  { label: 'Jul', value: 780 },
];

export const demoPipelineChart = [
  { label: 'Qualification', value: 320 },
  { label: 'Proposal', value: 450 },
  { label: 'Negotiation', value: 780 },
  { label: 'Won', value: 210 },
];

export const demoDashboardStats = {
  admin: [
    {
      id: 'rev',
      label: 'Month revenue',
      value: '₹7.8L',
      hint: 'Booked sales',
      trend: '+9.8% vs Jun',
    },
    {
      id: 'deals',
      label: 'Open deals',
      value: '3',
      hint: 'Active pipeline',
      trend: '₹15.5L value',
    },
    {
      id: 'stock',
      label: 'Low stock SKUs',
      value: '1',
      hint: 'Below reorder',
      trend: 'TLR-80',
    },
    {
      id: 'leave',
      label: 'Pending leave',
      value: '2',
      hint: 'Needs HR action',
      trend: 'This week',
    },
  ],
  sales: [
    {
      id: 'quota',
      label: 'Quota progress',
      value: '78%',
      hint: 'July target',
      trend: '₹7.8L of ₹10L',
    },
    {
      id: 'leads',
      label: 'Open leads',
      value: '4',
      hint: 'Needs follow-up',
      trend: '2 high score',
    },
    {
      id: 'quotes',
      label: 'Open quotations',
      value: '2',
      hint: 'Awaiting reply',
      trend: 'QT-441 priority',
    },
    {
      id: 'tasks',
      label: 'My tasks',
      value: '3',
      hint: 'Due this week',
      trend: '1 overdue',
    },
  ],
  hr: [
    {
      id: 'head',
      label: 'Headcount',
      value: '6',
      hint: 'Active roster',
      trend: '1 on leave',
    },
    {
      id: 'att',
      label: 'Attendance today',
      value: '83%',
      hint: 'Present + remote',
      trend: '1 absent',
    },
    {
      id: 'leave',
      label: 'Leave requests',
      value: '2',
      hint: 'Pending approval',
      trend: 'Action needed',
    },
    {
      id: 'pay',
      label: 'Payroll status',
      value: 'Draft',
      hint: 'July cycle',
      trend: 'Lock 28 Jul',
    },
  ],
};

export const demoPnL = [
  { label: 'Product sales', amount: 885000, type: 'income' as const },
  { label: 'Services', amount: 75000, type: 'income' as const },
  { label: 'COGS', amount: 410000, type: 'expense' as const },
  { label: 'Payroll', amount: 380000, type: 'expense' as const },
  { label: 'Operations', amount: 63000, type: 'expense' as const },
  { label: 'Marketing', amount: 35000, type: 'expense' as const },
];

export const demoSettings = {
  company: 'U&V Demo Enterprise',
  fiscalYear: 'Apr 2026 – Mar 2027',
  currency: 'INR',
  timezone: 'Asia/Kolkata',
  notifications: {
    dealAlerts: true,
    leaveAlerts: true,
    lowStock: true,
    invoiceReminders: true,
  },
};

export function getCustomerById(id: string) {
  return demoCustomers.find((customer) => customer.id === id);
}
